coderskins.desc1 = {}
coderskins.desc2 = {}

-- ===================================================================

coderskins.desc2 ["skin_Actual_Cat"  ] = "How Now Meow Wow"
coderskins.desc2 ["skin_Apple_Tree"  ] = "Apple a Day Hooray"
coderskins.desc2 ["skin_Patience"    ] = "Patience leads to focus"

-- ===================================================================

coderskins.list = {

    "skin_Chinese_Off_White"        ,
    "skin_Corona"                   ,
    "skin_Mumbo_Jumbo"              ,
    "skin_RedMinionToby"            ,
    "skin_SAF_Army1"                ,
    "skin_SAF_Army3G"               ,
    "skin_Hope"                     ,
    "skin_Jessa_PJs"                ,

    "skin_09SharkBoy"               ,
    "skin_Unspeakable"              ,
    "skin_LDShadow_Lady"            ,
    "skin_Steve_Watch"              ,
    "skin_Business_Kermit"          ,
    "skin_Stampy_Boots"             ,
    "skin_iBallistic_Squid"         ,
    "skin_MooseCraft"               ,
    "sscharacter_120"               ,

    "skin_Actual_Cat"               ,
    "skin_Apple_Tree"               ,
    "skin_Black_Panther"            ,
    "skin_Farmer_Green"             ,
    "skin_Patience"                 ,
    "skin_Bear"                     ,
    "skin_Hotdog"                   ,
    "skin_Robocop"                  ,
    "skin_Capt_America"             ,
    "skin_Queen_Elsa"               ,
    "skin_Cola"                     ,
    "skin_Santa"                    ,
    "skin_Tiger"                    ,
    "skin_Cool_Panda"               ,

    "skin_Athena"                   ,
    "skin_Brianna_Playz"            ,
    "skin_Chad_Wild_Clay"           ,
    "skin_Chara"                    ,
    "skin_Duck"                     ,
    "skin_Kata_Red_Hair"            ,
    "skin_Potion_Master"            ,
    "skin_Preston_Playz"            ,

    "skin_Batman"                   ,
    "skin_Battery"                  ,
    "skin_Bear_Overalls"            ,
    "skin_Bearded_Wizard"           ,
    "skin_Alejo_Facheraso"          ,
    "skin_Bee"                      ,
    "skin_Capt_Blue_Sparrow"        ,
    "skin_Doraemon"                 ,
    "skin_Green_Boy"                ,

    "skin_Grey_Dog"                 ,
    "skin_Hispanic_Napoleon"        ,
    "skin_King_Turtle"              ,
    "skin_Krypto"                   ,
    "skin_Pink_Tiger"               ,
    "skin_Recon_Expert"             ,
    "skin_Big_Bird"                 ,
    "skin_Gold_Cylon"               ,
    "skin_Gold_Knight"              ,
    "skin_Leo"                      ,
    "skin_Wonder_Woman"             ,
    "skin_Mr_Spock"                 ,
    "skin_Regular_Cylon"            ,
    "skin_Rosalyn_Potion_Master"    ,
    "skin_Red_Wolf_Boy"             ,
    "skin_Rosa"                     ,
    "skin_Shovel_Knight"            ,
    "skin_Wonder_Boy"               ,
    "skin_Boy_Red_Hoodie"           ,
    "skin_Boy_Water_Jacket"         ,
    "skin_Fire_Enderman"            ,
    "skin_Fox"                      ,
    "skin_Gamer_Guy"                ,
    "skin_Girl_Casual"              ,
    "skin_Good_Witch"               ,
    "skin_Green_Claus_Wizard"       ,
    "skin_Heather_Elf"              ,
    "skin_Hobbit"                   ,
    "skin_Jane_Foster"              ,
    "skin_Kyle_Rayner"              ,
    "skin_Lego_Person"              ,
    "skin_Lego_Spaceman"            ,
    "skin_Link"                     ,
    "skin_Luigi"                    ,
    "skin_Mario"                    ,
    "skin_Marley_Xia"               ,
    "skin_Mutant_Fox"               ,
    "skin_Owl"                      ,
    "skin_Pachilo155"               ,
    "skin_Pie"                      ,
    "skin_Pizza_Girl"               ,
    "skin_Polar_Bear"               ,
    "skin_Purple_Outfit"            ,
    "skin_Purple_Princess"          ,
    "skin_Quackin_Hood"             ,
    "skin_Rabbit"                   ,
    "skin_Rabbit_Coco"              ,
    "skin_Rainboots"                ,
    "skin_Squirrel"                 ,
    "skin_Stampy"                   ,
    "skin_Steampunk"                ,
    "skin_Super_Jack"               ,
    "skin_Supercow"                 ,
    "skin_Superpollo"               ,
    "skin_Thanatos"                 ,
    "skin_Trainer_Red"              ,
    "skin_Wafleman"                 ,
    "skin_White_Bear"               ,
    "skin_White_Dress"              ,
    "skin_Puppy"                    ,
    "skin_Bakugo"                   ,

    "sdskin_Blue_Girl"              ,
    "sdskin_Calinou"                ,
    "sdskin_Son_Goku"               ,
    "sdskin_StormChaser_30000"      ,
    "sdskin_oOChainLynxOo"          ,
    "sdskin_sdzen"                  ,

    "sscharacter_1"                 ,
    "sscharacter_100"               ,
    "sscharacter_101"               ,
    "sscharacter_102"               ,
    "sscharacter_103"               ,
    "sscharacter_106"               ,
    "sscharacter_107"               ,
    "sscharacter_108"               ,
    "sscharacter_109"               ,
    "sscharacter_110"               ,
    "sscharacter_111"               ,
    "sscharacter_113"               ,
    "sscharacter_114"               ,
    "sscharacter_116"               ,
    "sscharacter_118"               ,
    "sscharacter_119"               ,
    "sscharacter_121"               ,
    "sscharacter_122"               ,
    "sscharacter_123"               ,
    "sscharacter_126"               ,
    "sscharacter_129"               ,
    "sscharacter_13"                ,
    "sscharacter_132"               ,
    "sscharacter_133"               ,
    "sscharacter_134"               ,
    "sscharacter_135"               ,
    "sscharacter_136"               ,
    "sscharacter_14"                ,
    "sscharacter_140"               ,
    "sscharacter_141"               ,
    "sscharacter_142"               ,
    "sscharacter_143"               ,
    "sscharacter_146"               ,
    "sscharacter_148"               ,
    "sscharacter_149"               ,
    "sscharacter_15"                ,
    "sscharacter_150"               ,
    "sscharacter_151"               ,
    "sscharacter_152"               ,
    "sscharacter_16"                ,
    "sscharacter_2"                 ,
    "sscharacter_20"                ,
    "sscharacter_21"                ,
    "sscharacter_22"                ,
    "sscharacter_23"                ,
    "sscharacter_24"                ,
    "sscharacter_25"                ,
    "sscharacter_26"                ,
    "sscharacter_28"                ,
    "sscharacter_30"                ,
    "sscharacter_32"                ,
    "sscharacter_33"                ,
    "sscharacter_47"                ,
    "sscharacter_51"                ,
    "sscharacter_56"                ,
    "sscharacter_57"                ,
    "sscharacter_59"                ,
    "sscharacter_6"                 ,
    "sscharacter_64"                ,
    "sscharacter_66"                ,
    "sscharacter_70"                ,
    "sscharacter_71"                ,
    "sscharacter_73"                ,
    "sscharacter_75"                ,
    "sscharacter_78"                ,
    "sscharacter_80"                ,
    "sscharacter_81"                ,
    "sscharacter_83"                ,
    "sscharacter_84"                ,
    "sscharacter_85"                ,
    "sscharacter_90"                ,
    "sscharacter_99"                ,
    "uskins_1"                      ,
    "uskins_10"                     ,
    "uskins_11"                     ,
    "uskins_12"                     ,
    "uskins_13"                     ,
    "uskins_14"                     ,
    "uskins_16"                     ,
    "uskins_17"                     ,
    "uskins_18"                     ,
    "uskins_19"                     ,
    "uskins_2"                      ,
    "uskins_20"                     ,
    "uskins_21"                     ,
    "uskins_22"                     ,
    "uskins_23"                     ,
    "uskins_25"                     ,
    "uskins_26"                     ,
    "uskins_27"                     ,
    "uskins_28"                     ,
    "uskins_29"                     ,
    "uskins_3"                      ,
    "uskins_30"                     ,
    "uskins_31"                     ,
    "uskins_32"                     ,
    "uskins_33"                     ,
    "uskins_34"                     ,
    "uskins_35"                     ,
    "uskins_36"                     ,
    "uskins_37"                     ,
    "uskins_38"                     ,
    "uskins_39"                     ,
    "uskins_4"                      ,
    "uskins_40"                     ,
    "uskins_41"                     ,
    "uskins_45"                     ,
    "uskins_46"                     ,
    "uskins_47"                     ,
    "uskins_48"                     ,
    "uskins_5"                      ,
    "uskins_50"                     ,
    "uskins_51"                     ,
    "uskins_52"                     ,
    "uskins_53"                     ,
    "uskins_54"                     ,
    "uskins_55"                     ,
    "uskins_56"                     ,
    "uskins_58"                     ,
    "uskins_59"                     ,
    "uskins_6"                      ,
    "uskins_60"                     ,
    "uskins_61"                     ,
    "uskins_62"                     ,
    "uskins_63"                     ,
    "uskins_64"                     ,
    "uskins_65"                     ,
    "uskins_66"                     ,
    "uskins_68"                     ,
    "uskins_69"                     ,
    "uskins_70"                     ,
    "uskins_71"                     ,
    "uskins_72"                     ,
    "uskins_73"                     ,
    "uskins_74"                     ,
    "uskins_75"                     ,
    "uskins_77"                     ,
    "uskins_79"                     ,
    "uskins_8"                      ,
    "uskins_80"                     ,
    "uskins_81"                     ,
    "uskins_82"                     ,
    "uskins_83"                     ,
    "uskins_84"                     ,
    "uskins_85"                     ,
    "uskins_86"                     ,
    "uskins_87"                     ,
    "uskins_88"                     ,
    "uskins_89"                     ,
    "uskins_9"                      ,
    "uskins_90"                     ,
    "uskins_91"                     ,
    "uskins_92"                     ,
    "uskins_93"                     ,
    "uskins_94"                     ,
    "uskins_95"                     ,
    "uskins_96"                     ,
    "uskins_97"                     ,
    "uskins_98"                     ,
    "uskins_99"                     ,
    "uskins_103"                    ,
}

-- ===================================================================
-- Add local skins.

if  ocutil.bool_setting ("local_skins", true) then

    local ktable  = ocutil.vtable_to_ktable (coderskins.list)
    local dir     = coderskins.textdir
    local newlist = {}
    local ofname, dfname

    for _, ofname in ipairs(minetest.get_dir_list(dir, false))
    do
        ofname = ofname:gsub (".*/"         , "")
        ofname = ofname:gsub ("%.png$"      , "")
        dfname = ofname:gsub ("_preview.*$" , "")

        if  dfname == ofname and ktable [dfname] == nil then
            ktable [dfname] = true
            table.insert (newlist, dfname)
        end
    end

    for _, dfname in ipairs (coderskins.list) do
        table.insert (newlist, dfname)
    end

    coderskins.list = newlist
    ktable          = {}
    newlist         = {}
end

-- ===================================================================
-- End of file.
