#!/usr/bin/env python
'''
Count the number of meshes in OBJ files. In the Wavefront OBJ format,
these meshes are technically called "Objects" and the OBJ file can have
any number of them. They are created by the "o" command in the file.
'''
from __future__ import print_function
import sys
import os

SCRIPTS_DIR = os.path.dirname(os.path.realpath(__file__))
REPO_DIR = os.path.dirname(SCRIPTS_DIR)

sys.path.insert(0, REPO_DIR)  # let import find pyenliven when it's not installed

from pyenliven.objanalyze import main

if __name__ == "__main__":
    sys.exit(main())
