#!/bin/bash
rsync -rtv mtio:/opt/minebest/ ~/minebest-rsync --exclude "mtkit/minetest/" --exclude "assemble/" --exclude "mtkit0/"
# ^ exclude mtkit/minetest/ and assemble/ since they are remotely-built copies of the program.
# --info=progress2
code=$?
if [ $code -eq 0 ]; then
    echo "Updating ~/minebest-rsync...OK"
else
    echo "Updating ~/minebest-rsync...FAILED"
fi
cd ~/minebest-rsync
cat <<END

Next do:

cd ~/minebest-rsync/mtkit
bash -e mtcompile-libraries.sh build
perl mtcompile-program.pl --build --finetest --client
cd ~/minebest-rsync/mtkit/minetest/bin
nopackage install finetest --version rsync --caption "Finetest (rsync)"
END
