#!/usr/bin/env python
from __future__ import print_function
import sys
import os

SCRIPTS_DIR = os.path.dirname(os.path.realpath(__file__))
REPO_DIR = os.path.dirname(SCRIPTS_DIR)

sys.path.insert(0, REPO_DIR)  # let import find pyenliven when it's not installed

from pyenliven.mttexture import main

if __name__ == "__main__":
    sys.exit(main())
