#!/bin/sh
# Copyright 2017 expertmm
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

date_string=`date +%Y-%m-%d`
MT_WORLDS_PATH=$HOME/.minetest/worlds
cd $MT_WORLDS_PATH
ls
name_string=FCAGameAWorld-$date_string.tar.gz
echo "Attempting to create $name_string"
if [ ! -f "$name_string" ]
  then
  tar -czvf "$name_string" FCAGameAWorld
  if [ -f "$name_string" ]
    then
    echo "Successfully created $MT_WORLDS_PATH/$name_string"
  else
    echo "Failed to create $MT_WORLDS_PATH/$name_string"
  fi
else
  echo "Nothing to do. Already saved $MT_WORLDS_PATH/$name_string"
fi
