#!/bin/sh
# Copyright 2017 expertmm. License:
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

#First make sure all folders in $HOME/.minetest are created (I am not sure whether this is required!):
# minetestserver
# Mods were found at https://forum.minetest.net/viewforum.php?f=11


# * Git version uses /home/*/minetest/games and /usr/local/share/minetest/games but the latter is used for minetestserver (minetest-server package)
# Known Issues:
# * Must do the following if runs twice (run a third time to fix it):
if [ -d /usr/share/minetest/games/ENLIVEN/mods/3d_armor/minetest-3d_armor-master ]; then
  rm -Rf /usr/share/minetest/games/ENLIVEN/mods/3d_armor
fi
if [ -d /usr/share/minetest/games/ENLIVEN/mods/3d_armor/minetest-3d_armor-master ]; then
  rm -Rf /usr/share/minetest/games/ENLIVEN/mods/3d_armor
fi
if [ -d /usr/share/minetest/games/ENLIVEN/mods/plantlife_modpack/plantlife_modpack-master ]; then
  rm -Rf /usr/share/minetest/games/ENLIVEN/mods/plantlife_modpack
fi
Uberi=`ls /usr/share/minetest/games/ENLIVEN/mods/worldedit | grep Uberi`
if [ ! -z "$Uberi" ]; then
  # /usr/share/minetest/games/ENLIVEN/mods/worldedit/Uberi-Minetest-WorldEdit-3322ef9
  rm -Rf /usr/share/minetest/games/ENLIVEN/mods/worldedit
fi
if [ -d /usr/share/minetest/games/ENLIVEN/mods/mesecons/mesecons-master ]; then
  rm -Rf /usr/share/minetest/games/ENLIVEN/mods/mesecons
fi

# (Ubuntu 14.04 Trusty Tahr Server) folders were found using:
# cd /
# sudo find -name 'worlds' (worlds folder is in $HOME/.minetest)
# sudo find -name 'minimal' (stable build [such as 0.4.9 games folder is /usr/share/games/minetest/games, but git version games folder is /usr/local/share/minetest/games)

sudo echo "cached password."
# NOTE: minetest mods are ALWAYS ONLY installed on server
mtgame_name="minetest_game"
USR_SHARE_MINETEST=/usr/share/games/minetest
try_path="/usr/share/minetest"
if [ -d "$try_path" ]; then
  # Arch linux
  USR_SHARE_MINETEST="$try_path"
fi
if [ ! -d "$USR_SHARE_MINETEST" ]; then
  # IF git version is installed and regular one is NOT:
  try_path="/usr/local/share/minetest"
  if [ -d "$try_path" ]; then
    USR_SHARE_MINETEST="$try_path"
  fi
fi
# UNUSED (unknown use): MT_GAMES_DIR=$HOME/.minetest/mods
# intentionally skip the slash in the following line since $USR_SHARE_MINETEST already starts with one:
MT_BACKUP_GAMES_DIR=$HOME/Backup$USR_SHARE_MINETEST/games
MT_GAMES_DIR=$USR_SHARE_MINETEST/games
MT_MYGAME_BAK=$USR_SHARE_MINETEST/ENLIVEN_BAK
MT_MYGAME_NAME=ENLIVEN
MT_MYGAME_DIR=$MT_GAMES_DIR/$MT_MYGAME_NAME
# formerly MT_MYGAME_MODDIR:
MT_MYGAME_MODS_PATH=$MT_MYGAME_DIR/mods
MT_MYWORLD_NAME=FCAGameAWorld
MT_MYWORLD_DIR=$HOME/.minetest/worlds/$MT_MYWORLD_NAME
err_txt=$HOME/err-enliven.txt




# BACKUP THE WORLD:
sudo chown $USER "$MT_MYWORLD_DIR/world.mt"
sudo chown $USER "$MT_MYWORLD_DIR/world.mt.1st"
if [ ! -d "$MT_MYGAME_DIR" ]; then
  sudo mkdir "$MT_MYGAME_DIR"
fi
if [ -f "$MT_MYWORLD_DIR/world.mt.1st" ]; then
  echo "Already backed up world.mt to $MT_MYWORLD_DIR/world.mt.1st"
else
  cp "$MT_MYWORLD_DIR/world.mt" "$MT_MYWORLD_DIR/world.mt.1st"
  echo "The original world.mt is now backed up at $MT_MYWORLD_DIR/world.mt.1st"
fi
touch "$MT_MYWORLD_DIR/world.mt"
mv -f "$MT_MYWORLD_DIR/world.mt" "$MT_MYWORLD_DIR/world.mt.bak"

# REMAKE world.mt
cd
echo "gameid = $MT_MYGAME_NAME" > "world.mt"
sudo mv "world.mt" "$MT_MYWORLD_DIR/world.mt"
sudo chown $USER "$MT_MYWORLD_DIR/world.mt"
sudo chgrp $USER "$MT_MYWORLD_DIR/world.mt"
echo "backend = leveldb" >> "$MT_MYWORLD_DIR/world.mt"
#mv "world.mt" $MT_MYWORLD_DIR/world.mt

#MT_MYGAME_DIR (a Minetest "game") is the equivalent of a Minecraft modpack, however, in this case it is actually a collection of mods and modpacks, either of which can be in the mods folder

#cd
if [ ! -d "$HOME/Downloads" ]; then
  mkdir "$HOME/Downloads"
fi
cd "$HOME/Downloads"

if [ -d "$MT_MYGAME_BAK" ];
then
  echo "already backed up to $MT_MYGAME_BAK"
else
  sudo mv "$MT_MYGAME_DIR" "$MT_MYGAME_BAK"
  sudo mkdir "$MT_MYGAME_DIR"
fi


#sudo mkdir "$MT_MYGAME_DIR"
#sudo mkdir "$MT_MYGAME_MODS_PATH"
if [ ! -d "$MT_MYGAME_DIR/" ]; then
  echo "ERROR: failed to create $MT_MYGAME_DIR, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi
#sudo cp -R $USR_SHARE_MINETEST/games/$mtgame_name/mods/* "$MT_MYGAME_DIR/mods/"
if [ -d "$USR_SHARE_MINETEST/games/minetest" ]; then
  # Arch linux
  mtgame_name="minetest"
fi
sudo cp -R $USR_SHARE_MINETEST/games/$mtgame_name/* "$MT_MYGAME_DIR/"

#wget https://github.com/BlockMen/cme/releases/download/v2.3/cme-2_3-BlockMen.zip
#unzip cme-2_3-BlockMen.zip
#sudo mv cme "$MT_MYGAME_MODS_PATH/cme"
##DO NOT DO THIS (since cme is a modpack): echo "load_mod_cme = true" >> "$MT_MYWORLD_DIR/world.mt"
#echo "#cme Creatures MOB-Engine (cme) is a modpack" >> "$MT_MYWORLD_DIR/world.mt"

cd "$HOME/Downloads"
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=mobs_redo.zip
MTMOD_UNZ_NAME=mobs_redo-master
MTMOD_DEST_NAME=mobs
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
rm -Rvf $MTMOD_UNZ_NAME
#sudo rm -Rvf "$MTMOD_DEST_PATH"
echo "Installing TenPlus1's mobs.zip from https://github.com/tenplus1/mobs_redo/archive/master.zip"
echo "Installing TenPlus1's mobs.zip from https://github.com/tenplus1/mobs_redo/archive/master.zip" > mobs.zip.txt
#SEE ALSO RELEASE VERSION (must be logged in to download): https://forum.minetest.net/download/file.php?id=5282
#wget https://github.com/tenplus1/mobs/archive/master.zip
wget https://github.com/tenplus1/mobs_redo/archive/master.zip
mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi
echo "load_mod_mobs = true" >> "$MT_MYWORLD_DIR/world.mt"




cd "$HOME/Downloads"
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=mobs_monster.zip
MTMOD_UNZ_NAME=mobs_monster-master
MTMOD_DEST_NAME=mobs_monster
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
rm -Rvf $MTMOD_UNZ_NAME
wget https://github.com/tenplus1/mobs_monster/archive/master.zip
mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi
echo "load_mod_mobs_monster = true" >> "$MT_MYWORLD_DIR/world.mt"

cd "$HOME/Downloads"
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=mobs_animal.zip
MTMOD_UNZ_NAME=mobs_animal-master
MTMOD_DEST_NAME=mobs_animal
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
rm -Rvf $MTMOD_UNZ_NAME
wget https://github.com/tenplus1/mobs_animal/archive/master.zip
mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi
echo "load_mod_mobs_animal = true" >> "$MT_MYWORLD_DIR/world.mt"



#the following downloads protector (REDO version posted at https://forum.minetest.net/viewtopic.php?f=11&t=9376) not the original 2012 protector or 2012 fork of 2012 protector
#rm protector.zip
#wget https://forum.minetest.net/download/file.php?id=5046
#mv -f "file.php?id=5046" protector.zip
#USE GIT VERSION INSTEAD:
cd "$HOME/Downloads"
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=protector.zip
MTMOD_UNZ_NAME=protector-master
MTMOD_DEST_NAME=protector
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
rm -Rvf $MTMOD_UNZ_NAME
#as of 2016-02-20, CRASHES on default 0.4.9 minetesterver 0.4.13 git 2016-02-20:
wget https://github.com/tenplus1/protector/archive/master.zip
#expertmm fork to work in above situation:
#wget https://github.com/expertmm/protector/archive/master.zip
#results in UNKNOWN NODE for all protected blocks: wget https://github.com/MinetestForFun/protector/archive/master.zip
mv -f $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
#sudo rm -Rf "$MT_MYGAME_MODS_PATH/protector-master"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi

#sudo su -
#WRITEABLE_MINETEST_CONF=$USR_SHARE_MINETEST/games/$MT_MYGAME_NAME/minetest.conf
WRITEABLE_MINETEST_CONF=$HOME/minetest.conf
rm -f "$HOME/minetest.conf"
if [ ! -f "$USR_SHARE_MINETEST/games/$MT_MYGAME_NAME/minetest.conf" ]; then
  sudo cp "$USR_SHARE_MINETEST/games/$mtgame_name/minetest.conf" "$USR_SHARE_MINETEST/games/$MT_MYGAME_NAME/minetest.conf.1st"
fi
cp "$USR_SHARE_MINETEST/games/$mtgame_name/minetest.conf" "$WRITEABLE_MINETEST_CONF"
touch "$WRITEABLE_MINETEST_CONF"
#4080 since boundaries in chunkymap/singleimage.py (to be compatible with approximate browser max image size) are -4096 to 4096
echo "map_generation_limit = 4096" >> "$WRITEABLE_MINETEST_CONF"
#NOTE: map_generation_limit (aka world boundary, world border, or world limit) must be divisible by 64, so for example, 5000 results in invisible wall at 4928
echo "protector_radius = 7" >> "$WRITEABLE_MINETEST_CONF"
echo "protector_flip = true" >> "$WRITEABLE_MINETEST_CONF"
echo "protector_pvp = true" >> "$WRITEABLE_MINETEST_CONF"
echo "protector_pvp_spawn = 10" >> "$WRITEABLE_MINETEST_CONF"
echo "protector_drop = false" >> "$WRITEABLE_MINETEST_CONF"
echo "protector_hurt = 3" >> "$WRITEABLE_MINETEST_CONF"
echo "default_privs = interact,shout,home" >> "$WRITEABLE_MINETEST_CONF"
echo "max_users = 50" >> "$WRITEABLE_MINETEST_CONF"
echo "motd = \"Actions and chat messages are logged. Use inventory to see recipes (use web for live map if available).\""  >> "$WRITEABLE_MINETEST_CONF"
echo "disallow_empty_passwords = true" >> "$WRITEABLE_MINETEST_CONF"
echo "secure.trusted_mods = advanced_npc" >> "$WRITEABLE_MINETEST_CONF"
echo "server_dedicated = false" >> "$WRITEABLE_MINETEST_CONF"
echo "hudbars_bar_type = statbar_modern" >> "$WRITEABLE_MINETEST_CONF"
sudo mv -f $HOME/minetest.conf "$USR_SHARE_MINETEST/games/$MT_MYGAME_NAME/minetest.conf"
echo "load_mod_protector = true" >> $MT_MYWORLD_DIR/world.mt


cd "$HOME/Downloads"
#MTMOD_DL_ZIP=master.tar.gz
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=xban2.zip
#MTMOD_UNZ_NAME=minetest-xban2-master
MTMOD_UNZ_NAME=xban2-master
MTMOD_DEST_NAME=xban2
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
rm -Rvf $MTMOD_UNZ_NAME
#wget https://github.com/kaeza/minetest-xban2/archive/master.tar.gz
wget https://github.com/minetest-mods/xban2/archive/master.zip
mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
#tar -xzvf $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
# As http://wiki.minetest.net/Installing_Mods specifies, a mod MUST be renamed to official name as in the official thread of the mod:
mv $MTMOD_UNZ_NAME $MTMOD_DEST_NAME
sudo mv $MTMOD_DEST_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi

echo "load_mod_xban2 = true" >> "$MT_MYWORLD_DIR/world.mt"

cd "$HOME/Downloads"
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=areas.zip
MTMOD_UNZ_NAME=areas-master
MTMOD_DEST_NAME=areas
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
echo "Installing ShadowNinja's <https://forum.minetest.net/viewtopic.php?t=7239>"
echo "Installing ShadowNinja's <https://forum.minetest.net/viewtopic.php?t=7239>" >> $MTMOD_SRC_ZIP.txt
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
rm -Rvf $MTMOD_UNZ_NAME
wget https://github.com/ShadowNinja/areas/archive/master.zip
mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi
echo "load_mod_areas = true" >> "$MT_MYWORLD_DIR/world.mt"

if [ -f "$MT_MYGAME_DIR/game.conf.1st" ]; then
  echo "Already backed up $MT_MYGAME_DIR/game.conf to $MT_MYGAME_DIR/game.conf.1st"
else
  sudo cp "$MT_MYGAME_DIR/game.conf" "$MT_MYGAME_DIR/game.conf.1st"
fi
echo "name = $MT_MYGAME_NAME" > "$HOME/game.conf"
sudo mv -f "$HOME/game.conf" "$MT_MYGAME_DIR/game.conf"
#su -
#FAILS: echo "name = $MT_MYGAME_NAME" > "$MT_MYGAME_DIR/game.conf"
#sudo nano "$MT_MYGAME_DIR/game.conf"
echo ""
echo "You should see $MT_MYGAME_NAME in the list below if the game was configured properly:"
minetestserver --gameid list
echo ""


#ls "$MT_MYGAME_MODS_PATH"
if [ ! -d "$MT_BACKUP_GAMES_DIR" ]; then
  mkdir -p "$MT_BACKUP_GAMES_DIR"
#-p to make parent recursively
fi
first_suffix="_1st"
if [ -d "$MT_BACKUP_GAMES_DIR/$mtgame_name$first_suffix" ]; then
  echo "already backed up $USR_SHARE_MINETEST/games/$mtgame_name"
else
  sudo cp -R "$USR_SHARE_MINETEST/games/$mtgame_name" "$MT_BACKUP_GAMES_DIR/"
fi
#sudo mv "$USR_SHARE_MINETEST/games/fca-game-a" "$USR_SHARE_MINETEST/games/$mtgame_name"

#UNUSED, and is based on a much older version of minetest_game:
#MTMOD_DL_ZIP=master.zip
#MTMOD_SRC_ZIP=carbone-ng.zip
#MTMOD_UNZ_NAME=carbone-ng-master
#MTMOD_DEST_NAME=carbone-ng
##MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#MTMOD_DEST_PATH=$MT_GAMES_DIR/$MTMOD_DEST_NAME
##if [ -d "$MTMOD_UNZ_NAME" ]; then
#rm -Rf $MTMOD_UNZ_NAME
##fi
#if [ -f "$MTMOD_DL_ZIP" ]; then
#  rm -f "$MTMOD_DL_ZIP"
#fi
#if [ -f "$MTMOD_SRC_ZIP" ]; then
#  rm -f "$MTMOD_SRC_ZIP"
#fi
#cd "$HOME/Downloads"
#wget https://github.com/Calinou/carbone-ng/archive/master.zip
#mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
#unzip $MTMOD_SRC_ZIP
#sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
#if [ ! -d "$MTMOD_DEST_PATH" ]; then
#  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
#  cat $err_txt
#  exit 1
#fi

#sudo cp -R /usr/share/games/minetest/games/carbone-ng /usr/local/share/minetest/games/carbone-ng

#IF git version is installed:
#if [ -d "/usr/local/share/minetest/games" ];
#then
#sudo cp -R $USR_SHARE_MINETEST/games/$MT_MYGAME_NAME /usr/local/share/minetest/games/$MT_MYGAME_NAME
#sudo mv $HOME/Downloads/cme /usr/local/share/minetest/games/$MT_MYGAME_NAME/mods/cme
#sudo mv $HOME/Downloads/protector /usr/local/share/minetest/games/$MT_MYGAME_NAME/mods/protector
#fi

# actually farming REDO as per https://forum.minetest.net/viewtopic.php?f=11&t=9019
#wget https://forum.minetest.net/download/file.php?id=5045
#mv "file.php?id=5045" farming.zip
#unzip farming.zip
#sudo rm -Rf $MT_MYGAME_MODS_PATH/farming
#sudo mv farming $MT_MYGAME_MODS_PATH/farming
# breaks 0.4.13 dev version 2016-02-17 (says height_max deprecated, use y_max; and later
#2016-02-17 11:10:19: ERROR[Main]: ModError: Failed to load and run script from $USR_SHARE_MINETEST/games/enliven/mods/farming/init.lua:
#2016-02-17 11:10:19: ERROR[Main]: ...share/minetest/games/enliven/mods/farming/pumpkin.lua:78: attempt to perform arithmetic on field 'LIGHT_MAX' (a nil value)
#2016-02-17 11:10:19: ERROR[Main]: stack traceback:
#2016-02-17 11:10:19: ERROR[Main]:       ...share/minetest/games/enliven/mods/farming/pumpkin.lua:78: in main chunk
#2016-02-17 11:10:19: ERROR[Main]:       [C]: in function 'dofile'
#2016-02-17 11:10:19: ERROR[Main]:       ...al/share/minetest/games/enliven/mods/farming/init.lua:65: in main chunk
# Remove & overwrite Farming REDO since it crashes 0.4.13 git 2016-02-16:
#sudo rm -Rf $MT_MYGAME_MODS_PATH/farming
#sudo cp -R $USR_SHARE_MINETEST/games/$mtgame_name/mods/farming $MT_MYGAME_MODS_PATH/farming

MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=unified_inventory.zip
MTMOD_UNZ_NAME=unified_inventory-master
MTMOD_DEST_NAME=unified_inventory
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
wget https://github.com/minetest-technic/unified_inventory/archive/master.zip
mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi
echo "load_mod_unified_inventory = true" >> $MT_MYWORLD_DIR/world.mt


MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=technic.zip
MTMOD_UNZ_NAME=technic-master
MTMOD_DEST_NAME=technic
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
if [ -d "$MTMOD_DEST_PATH" ]; then
 rm -Rf "$MTMOD_DEST_PATH"
fi
#wget https://github.com/minetest-technic/technic/archive/master.zip
wget https://github.com/minetest-mods/technic/archive/master.zip
mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi
echo "load_mod_technic = true" >> $MT_MYWORLD_DIR/world.mt



#uninstall:
#if [ -d "$MT_MYGAME_MODS_PATH/unified_inventory" ]; then
#  if [ -d "$HOME/Backup/unified_inventory" ]; then
#    rm -Rf "$HOME/Backup/unified_inventory"
#  fi
#  sudo mv "$MT_MYGAME_MODS_PATH/unified_inventory" "$HOME/Backup/unified_inventory"
#fi
#reinstall:
#sudo mv "$HOME/Backup/unified_inventory" "$MT_MYGAME_MODS_PATH/unified_inventory"

MTMOD_DL_ZIP=treasurer0.2.0.zip
MTMOD_SRC_ZIP=treasurer0.2.0.zip
MTMOD_UNZ_NAME=treasurer
MTMOD_DEST_NAME=treasurer
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -f "tsm_gift_example" ]; then
  rm "tsm_gift_example"
fi
if [ -d "tsm_gift_example" ]; then
  rm -Rf "tsm_gift_example"
fi
if [ -d "tsm_chests_example" ]; then
  rm -Rf "tsm_chests_example"
fi
if [ -d "trm_default_example" ]; then
  rm -Rf "trm_default_example"
fi
if [ -d "tsm_default_example" ]; then
  rm -Rf "tsm_default_example"
fi
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
wget http://axlemedia.net/abiyahh/users/Wuzzy/downloads/treasurer0.2.0.zip
unzip $MTMOD_SRC_ZIP
sudo mv -f $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi
echo "load_mod_treasurer = true" >> $MT_MYWORLD_DIR/world.mt


#DEPRECATED, replaced by spawners (which includes pyramids worldgen mod)
#MTMOD_DL_ZIP=ebf839579197053b2ead85072757f23158960319.zip
#MTMOD_SRC_ZIP=tsm_pyramids.zip
#MTMOD_UNZ_NAME=tsm_pyramids-*
#MTMOD_DEST_NAME=tsm_pyramids
#MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
##if [ -d "$MTMOD_UNZ_NAME" ]; then
#rm -Rf $MTMOD_UNZ_NAME
##fi
#if [ -f "$MTMOD_DL_ZIP" ]; then
#  rm -f "$MTMOD_DL_ZIP"
#fi
#if [ -f "$MTMOD_SRC_ZIP" ]; then
#  rm -f "$MTMOD_SRC_ZIP"
#fi
#wget http://repo.or.cz/w/minetest_pyramids/tsm_pyramids.git/snapshot/ebf839579197053b2ead85072757f23158960319.zip
#mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
#unzip $MTMOD_SRC_ZIP
#sudo mv -f $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
#if [ ! -d "$MTMOD_DEST_PATH" ]; then
#  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
#  cat $err_txt
#  exit 1
#fi

cd "$HOME/Downloads"
MTMOD_DL_ZIP=akiba-*
wget http://git.akiba.fr:81/minetest/akiba/repository/archive.zip?ref=af571404a27a2cb06842c644930344f565a0b786
rm -f $MTMOD_DL_ZIP

wget https://github.com/MinetestForFun/server-minetestforfun/raw/master/mods/trm_pyramids/depends.txt
wget https://github.com/MinetestForFun/server-minetestforfun/raw/master/mods/trm_pyramids/init.lua
wget https://github.com/MinetestForFun/server-minetestforfun/raw/master/mods/trm_pyramids/more_trms.lua

#Wuzzy's hudbars (no builtin bars; used by sprint, hbhunger, and hbarmor) https://forum.minetest.net/viewtopic.php?f=11&t=11153&hilit=hunger
cd $HOME/Downloads
#MTMOD_DL_ZIP=master.zip
#MTMOD_SRC_ZIP=hudbars.zip
MTMOD_UNZ_NAME=minetest_hudbars
MTMOD_DEST_NAME=hudbars
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
#if [ -f $MTMOD_DL_ZIP ]; then
#  rm -f $MTMOD_DL_ZIP
#fi
#if [ -f $MTMOD_SRC_ZIP ]; then
#  rm -f $MTMOD_SRC_ZIP
#fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
git clone git://repo.or.cz/minetest_hudbars.git
#aka http://repo.or.cz/w/minetest_hudbars.git
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi


if [ ! -d "$MT_MYGAME_MODS_PATH/hudbars" ]; then
cd "$HOME/Downloads"
#MTMOD_DL_ZIP=hud_hunger-2_x_1-BlockMen.zip
#MTMOD_SRC_ZIP=hud_hunger-2_x_1-BlockMen.zip
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=hud_hunger.zip
MTMOD_UNZ_NAME=hud_hunger
MTMOD_DEST_NAME=hud_hunger
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#in case someone installed the mods apart from the modpack:
if [ -d "$MT_MYGAME_MODS_PATH/hud" ]; then
  sudo rm -Rf "$MT_MYGAME_MODS_PATH/hud"
fi
if [ -d "$MT_MYGAME_MODS_PATH/hunger" ]; then
  sudo rm -Rf "$MT_MYGAME_MODS_PATH/hunger"
fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
rm -Rvf $MTMOD_UNZ_NAME
#BlockMen's is not maintained, & has problem on hud/buildin line 79 (crash since air can be nil)
#wget https://github.com/BlockMen/hud_hunger/releases/download/2.x.1/hud_hunger-2_x_1-BlockMen.zip
#FozLand's has a couple fixes
#wget https://github.com/FozLand/hud_hunger/archive/master.zip
#tenplus1's fixes nil air, nil player, and sprint
wget https://github.com/tenplus1/hud_hunger/archive/master.zip
unzip $MTMOD_SRC_ZIP
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
sudo rm "$MTMOD_DEST_PATH/hunger/functions_UNUSED_sprint.lua"
sudo mv "$MTMOD_DEST_PATH/hunger/functions.lua" "$MTMOD_DEST_PATH/hunger/functions_UNUSED_sprint.lua"
sudo mv "$MTMOD_DEST_PATH/hunger/functions_(nosprint).lua" "$MTMOD_DEST_PATH/hunger/functions.lua"
sudo rm "$MTMOD_DEST_PATH/hunger/init_UNUSED_sprint.lua"
sudo mv "$MTMOD_DEST_PATH/hunger/init.lua" "$MTMOD_DEST_PATH/hunger/init_UNUSED_sprint.lua"
sudo mv "$MTMOD_DEST_PATH/hunger/init_(nosprint).lua" "$MTMOD_DEST_PATH/hunger/init.lua"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi
# END IF no hudbars mod
else
if [ -d "$MT_MYGAME_MODS_PATH/hud_hunger" ]; then
sudo rm -Rvf "$MT_MYGAME_MODS_PATH/hud_hunger"
fi
fi

#Wuzzy's hbarmor for hudbars https://forum.minetest.net/viewtopic.php?f=11&t=11153&hilit=hunger
cd $HOME/Downloads
#MTMOD_DL_ZIP=master.zip
#MTMOD_SRC_ZIP=hudbars.zip
MTMOD_UNZ_NAME=minetest_hbarmor
MTMOD_DEST_NAME=hbarmor
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
#if [ -f $MTMOD_DL_ZIP ]; then
#  rm -f $MTMOD_DL_ZIP
#fi
#if [ -f $MTMOD_SRC_ZIP ]; then
#  rm -f $MTMOD_SRC_ZIP
#fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
git clone git://repo.or.cz/minetest_hbarmor.git
#aka http://repo.or.cz/minetest_hbarmor.git/snapshot/bfc5f8cbb560eff6f206eec3242f8401d11c1310.zip
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi

#Wuzzy's hbhunger for hudbars https://forum.minetest.net/viewtopic.php?f=11&t=11153&hilit=hunger
cd $HOME/Downloads
#MTMOD_DL_ZIP=master.zip
#MTMOD_SRC_ZIP=hbhunger.zip
MTMOD_UNZ_NAME=minetest_hbhunger
MTMOD_DEST_NAME=hbhunger
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
#if [ -f $MTMOD_DL_ZIP ]; then
#  rm -f $MTMOD_DL_ZIP
#fi
#if [ -f $MTMOD_SRC_ZIP ]; then
#  rm -f $MTMOD_SRC_ZIP
#fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
git clone git://repo.or.cz/minetest_hbhunger.git
#aka http://repo.or.cz/minetest_hbhunger.git/snapshot/da70eba4fd0a9644cdb0a5b0d7ee3d93f7e61acf.zip
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi


cd "$HOME/Downloads"
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=moreblocks.zip
MTMOD_UNZ_NAME=moreblocks-master
MTMOD_DEST_NAME=moreblocks
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -d "moreblocks-master" ]; then
  rm -Rf moreblocks-master
fi
if [ -f "master.zip" ]; then
  rm master.zip
fi
if [ -f "moreblocks.zip" ]; then
  rm moreblocks.zip
fi
#wget https://gitorious.com/calinou/moreblocks/archive/master.zip
wget https://github.com/minetest-mods/moreblocks/archive/master.zip
mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
sudo mv -f $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi


MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=pipeworks.zip
MTMOD_UNZ_NAME=pipeworks-master
MTMOD_DEST_NAME=pipeworks
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -d "$MTMOD_UNZ_NAME" ]; then
  rm -Rf "$MTMOD_UNZ_NAME"
fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
wget https://github.com/VanessaE/pipeworks/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi


MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=plantlife_modpack.zip
MTMOD_UNZ_NAME=plantlife_modpack-master
MTMOD_DEST_NAME=plantlife_modpack
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -d "$MTMOD_UNZ_NAME" ]; then
  rm -Rf "$MTMOD_UNZ_NAME"
fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
wget https://github.com/VanessaE/plantlife_modpack/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi



#NOTE: https://forum.minetest.net/viewtopic.php?f=9&t=12368
# has blocks, but OTHER ONE ONLY HAS DYE (not used): https://forum.minetest.net/viewtopic.php?f=9&t=11287
cd "$HOME/Downloads"
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=lapis_Napiophelios.zip
MTMOD_UNZ_NAME=LapisLazuli-master
MTMOD_DEST_NAME=lapis
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -d "$MTMOD_UNZ_NAME" ]; then
  rm -Rf "$MTMOD_UNZ_NAME"
fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
wget https://github.com/Napiophelios/LapisLazuli/archive/master.zip
mv "$MTMOD_DL_ZIP" "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi

#cd "$HOME/Downloads"
#MTMOD_DL_ZIP=master.zip
#MTMOD_SRC_ZIP=helicopter.zip
#MTMOD_UNZ_NAME=helicopter-master
#MTMOD_DEST_NAME=helicopter
#if [ -f "$MTMOD_DL_ZIP" ]; then
#  rm -f "$MTMOD_DL_ZIP"
#fi
#if [ -f "$MTMOD_SRC_ZIP" ]; then
#  rm -f "$MTMOD_SRC_ZIP"
#fi
#wget https://github.com/SokolovPavel/helicopter/archive/master.zip
#mv "$MTMOD_DL_ZIP" "$MTMOD_SRC_ZIP"
#unzip "$MTMOD_SRC_ZIP"
#sudo mv "$MTMOD_UNZ_NAME" "$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME"
#UNINSTALL since crashes 0.4.13 git 2016-02:
#sudo mv "$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME" "$MTMOD_UNZ_NAME"

MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=biome_lib.zip
MTMOD_UNZ_NAME=biome_lib-master
MTMOD_DEST_NAME=biome_lib
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -d "$MTMOD_UNZ_NAME" ]; then
  rm -Rf "$MTMOD_UNZ_NAME"
fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
wget https://github.com/VanessaE/biome_lib/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi

MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=moretrees.zip
MTMOD_UNZ_NAME=moretrees-master
MTMOD_DEST_NAME=moretrees
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -d "$MTMOD_UNZ_NAME" ]; then
  rm -Rf "$MTMOD_UNZ_NAME"
fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
wget https://github.com/VanessaE/moretrees/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi


MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=minetest-3d_armor.zip
MTMOD_UNZ_NAME=minetest-3d_armor-master
MTMOD_DEST_NAME=3d_armor
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -d "$MTMOD_UNZ_NAME" ]; then
  rm -Rf "$MTMOD_UNZ_NAME"
fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
wget https://github.com/stujones11/minetest-3d_armor/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi
#mv minetest-3d_armor-master minetest-3d_armor_MODPACK
#sudo mv minetest-3d_armor_MODPACK/wieldview $MT_MYGAME_MODS_PATH/wieldview
#sudo mv minetest-3d_armor_MODPACK/3d_armor $MT_MYGAME_MODS_PATH/3d_armor
#sudo mv minetest-3d_armor_MODPACK/shields $MT_MYGAME_MODS_PATH/shields
#echo "load_mod_wieldview = true" >> $MT_MYWORLD_DIR/world.mt
echo "load_mod_3d_armor = true" >> $MT_MYWORLD_DIR/world.mt
#echo "load_mod_shields = true" >> $MT_MYWORLD_DIR/world.mt
#echo "load_mod_technic_armor = false" >> $MT_MYWORLD_DIR/world.mt

cd ~/Downloads
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=caverealms.zip
MTMOD_UNZ_NAME=minetest-caverealms-master
MTMOD_DEST_NAME=caverealms
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -d "$MTMOD_UNZ_NAME" ]; then
  rm -Rf "$MTMOD_UNZ_NAME"
fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  rm -Rf "$MTMOD_DEST_PATH"
fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
wget https://github.com/HeroOfTheWinds/minetest-caverealms/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi

#if [ -f "master.zip" ]; then
  #rm master.zip
#fi
#wget https://github.com/Splizard/minetest-mod-snow/archive/master.zip
#mv master.zip snow.zip
#unzip snow.zip
#mv minetest-mod-snow-master snow
#sudo mv snow "$MT_MYGAME_MODS_PATH/snow"
# (since snow prevents server 0.4.13 git 2016-02-16 from starting):
#sudo mv $MT_MYGAME_MODS_PATH/snow $HOME/Downloads/snow

MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=moreores.zip
MTMOD_UNZ_NAME=moreores-master
MTMOD_DEST_NAME=moreores
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -d "$MTMOD_UNZ_NAME" ]; then
  rm -Rf "$MTMOD_UNZ_NAME"
fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
wget https://github.com/Calinou/moreores/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi

MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=sprint.zip
MTMOD_UNZ_NAME=sprint-master
MTMOD_DEST_NAME=sprint
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -d "$MTMOD_UNZ_NAME" ]; then
  rm -Rf "$MTMOD_UNZ_NAME"
fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
# sprint https://forum.minetest.net/viewtopic.php?f=9&t=9650
wget https://github.com/GunshipPenguin/sprint/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi

#the following is NOT needed, since one of the mods above adds the home gui and home permission (but no /home or /sethome command)
#if [ -f "master.zip" ]; then
  #rm master.zip
#fi
#wget https://github.com/cornernote/minetest-home_gui/archive/master.zip
#mv master.zip minetest-home_gui.zip
#unzip minetest-home_gui.zip
#sudo mv minetest-home_gui-master/home_gui "$MT_MYGAME_MODS_PATH/home_gui"

#echo "snow:snow 255 255 255" >> $HOME/minetest/util/colors.txt
#echo "snow:snow_block 255 255 255" >> $HOME/minetest/util/colors.txt
#echo "snow:ice 144 217 234" >> $HOME/minetest/util/colors.txt

#sh chunkymap/install-ubuntu.sh

cd "$HOME/Downloads"
#does NOT have a zip extension when downloaded via wget:
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=mesecons_modpack.zip
MTMOD_UNZ_NAME=mesecons-master
MTMOD_DEST_NAME=mesecons
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
rm -Rf minetest-mods-mesecons-*
rm -Rf ""
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
wget https://github.com/minetest-mods/mesecons/archive/master.zip
mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
sudo mv -f $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to create $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi

############ REQUIRES MESECONS ############
##### NEEDED since carts in minetest_game added much of this functionality but not yet startstoprail or detectorrail #####
#See also carts plus, a fork of carts (the PilzAdam one later added to minetest_game) https://github.com/Kilarin/minetest-mod-carts-plus which adds touring rails, a hand break, switching, and view locking
#NOTE: boost_cart has handbrake (back key), Rail junction switching with the 'right-left' walking keys
#So either install this mod or do (less functionality):
#minetest.register_alias("boost_cart:detectorrail", "carts:rail")
#minetest.register_alias("boost_cart:startstoprail", "carts:powerrail")
#-- carts:brakerail
#-- carts:cart
#-- carts:powerrail
#-- carts:rail
cd "$HOME/Downloads"
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=boost_cart.zip
MTMOD_UNZ_NAME=boost_cart-master
MTMOD_DEST_NAME=boost_cart
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  rm -Rf "$MTMOD_DEST_PATH"
fi
wget https://github.com/SmallJoker/boost_cart/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
#https://forum.minetest.net/viewtopic.php?f=11&t=10172&hilit=boost+cart
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi

cd "$HOME/Downloads"
#MTMOD_DL_ZIP=archive.zip
MTMOD_DL_ZIP=master.zip
#MTMOD_SRC_ZIP=throwing_Echoes91.zip
MTMOD_SRC_ZIP=throwing_MinetestForFun.zip
MTMODPACK_UNZ_NAME=server-minetestforfun-master
MTMOD_UNZ_NAME=server-minetestforfun-master/mods/throwing
MTMOD_DEST_NAME=throwing
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -d "$MTMOD_DEST_PATH" ]; then
  echo "Removing old version of throwing..."
  sudo rm -Rf $MTMOD_DEST_PATH
fi
echo "Installing MinetestForFun's PvP fork of Echoes91's (NOT Echoes91's Throwing enhanced NOT PilzAdam's NOT Jeija's) Throwing <https://forum.minetest.net/viewtopic.php?f=11&t=11437>"
if [ -f "throwing_Echoes91.zip" ]; then
  rm throwing_Echoes91.zip
fi
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
if [ -d "$MTMODPACK_UNZ_NAME" ]; then
  rm -Rf $MTMODPACK_UNZ_NAME
fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
#wget https://github.com/PilzAdam/throwing/zipball/master
#wget https://gitlab.com/echoes91/throwing/repository/archive.zip
wget https://github.com/MinetestForFun/server-minetestforfun/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi

cd "$HOME/Downloads"
#MTMOD_DL_ZIP=*
MTMOD_SRC_ZIP=tsm_mines.zip
#MTMOD_UNZ_NAME=tsm_mines-*
MTMOD_UNZ_NAME=tsm_mines
MTMOD_DEST_NAME=tsm_mines
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -d tsm_mines ]; then
  rm -Rf tsm_mines
fi
if [ -f tsm_mines.zip ]; then
  rm tsm_mines.zip
fi
if [ -d tsm_mines_zipped ]; then
  rm -Rf tsm_mines_zipped
fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
#if [ ! -d tsm_mines_zipped ]; then
#  mkdir tsm_mines_zipped
#fi
#cd tsm_mines_zipped
#wget http://repo.or.cz/w/tsm_mines.git/snapshot/7ff7f5c24c05b463ecfbf80cbd5e8f6f4a4f4520.zip
#wget http://repo.or.cz/tsm_mines.git/shortlog/refs/heads/master
#mv master master.zip
#unzip master.zip
#unzip *
git clone git://repo.or.cz/tsm_mines.git
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi

cd "$HOME/Downloads"
#MTMOD_DL_ZIP=*
MTMOD_SRC_ZIP=tsm_railcorridors.zip
#MTMOD_UNZ_NAME=tsm_railcorridors-*
MTMOD_UNZ_NAME=tsm_railcorridors
MTMOD_DEST_NAME=tsm_railcorridors
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -d $MTMOD_DEST_NAME ]; then
  rm -Rf $MTMOD_DEST_NAME
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
if [ -d tsm_railcorridors_zipped ]; then
  rm -Rf tsm_railcorridors_zipped
fi
#if [ ! -d tsm_railcorridors_zipped ]; then
#  mkdir tsm_railcorridors_zipped
#fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
#cd "tsm_railcorridors_zipped"
#wget http://repo.or.cz/w/RailCorridors/tsm_railcorridors.git/snapshot/7fab088e813b777ceddaa56fc980ccc55b0b3f01.zip
git clone git://repo.or.cz/RailCorridors/tsm_railcorridors.git
#unzip *
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi

cd "$HOME/Downloads"
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=fishing_Minetestforfun.zip
MTMOD_UNZ_NAME=fishing-master
MTMOD_DEST_NAME=fishing
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
echo "Installing Minetestforfun's (NOT wulfsdad's) fishing <https://forum.minetest.net/viewtopic.php?f=11&t=13659>"
echo "Installing Minetestforfun's (NOT wulfsdad's) fishing <https://forum.minetest.net/viewtopic.php?f=11&t=13659>" >> $MTMOD_SRC_ZIP.txt
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
wget https://github.com/MinetestForFun/fishing/archive/master.zip
mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi

cd "$HOME/Downloads"
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=compassgps.zip
MTMOD_UNZ_NAME=compassgps-master
MTMOD_DEST_NAME=compassgps
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
echo "Installing Kilarin's compassgps (NOT TeTpaAka, nor Echo, nor PilzAdam compass) <https://forum.minetest.net/viewtopic.php?t=9373>"
echo "Installing Kilarin's compassgps (NOT TeTpaAka, nor Echo, nor PilzAdam compass) <https://forum.minetest.net/viewtopic.php?t=9373>" >> $MTMOD_SRC_ZIP.txt
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
wget https://github.com/Kilarin/compassgps/archive/master.zip
mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi

MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=whitelist.zip
MTMOD_UNZ_NAME=whitelist-master
MTMOD_DEST_NAME=whitelist
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
echo "Installing ShadowNinja's whitelist <https://forum.minetest.net/viewtopic.php?id=8434>"
echo "Installing ShadowNinja's whitelist <https://forum.minetest.net/viewtopic.php?id=8434>" >> $MTMOD_SRC_ZIP.txt
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
wget https://github.com/ShadowNinja/whitelist/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi


MTMOD_DEST_NAME=playereffects
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -f playereffects_Wuzzy.zip ]; then
  rm playereffects_Wuzzy.zip
fi
if [ -f "3b860c74ae9803f9a979b12c6f6beb74f96ae62c.zip" ]; then
  rm "3b860c74ae9803f9a979b12c6f6beb74f96ae62c.zip"
fi
if [ -d "minetest_playereffects-3b860c7" ]; then
  rm -Rf minetest_playereffects-3b860c7
fi
if [ -d "minetest_playereffects" ]; then
  rm -Rf minetest_playereffects
fi
cd "$HOME/Downloads"
git clone http://repo.or.cz/minetest_playereffects.git
#wget http://repo.or.cz/minetest_playereffects.git/snapshot/3b860c74ae9803f9a979b12c6f6beb74f96ae62c.zip
#mv "3b860c74ae9803f9a979b12c6f6beb74f96ae62c.zip" playereffects_Wuzzy.zip
#unzip playereffects_Wuzzy.zip
#sudo mv minetest_playereffects* "$MT_MYGAME_MODS_PATH/playereffects"
sudo mv minetest_playereffects "$MTMOD_DEST_PATH"

#Byakuren. <https://forum.minetest.net/viewtopic.php?f=9&t=13941>.

#monoidal_effects by Byakuren [raymoo on GitHub] is deprecated by player_monoids by Byakuren [raymoo on GitHub] +playereffects by Wuzzy
#according to the author https://forum.minetest.net/viewtopic.php?t=13941
#cd $HOME\Downloads
#MTMOD_DL_ZIP=master.zip
#MTMOD_SRC_ZIP=monoidal_effects.zip
#MTMOD_UNZ_NAME=monoidal_effects-master
#MTMOD_DEST_NAME=monoidal_effects
#MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
##if [ -d "$MTMOD_UNZ_NAME" ]; then
#rm -Rf $MTMOD_UNZ_NAME
##fi
#if [ -f $MTMOD_DL_ZIP ]; then
#  rm -f $MTMOD_DL_ZIP
#fi
#if [ -f $MTMOD_SRC_ZIP ]; then
#  rm $MTMOD_SRC_ZIP
#fi
#wget https://github.com/minetest-mods/monoidal_effects/archive/master.zip
#mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
#unzip $MTMOD_SRC_ZIP
#sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
#if [ ! -d "$MTMOD_DEST_PATH" ]; then
#  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
#  cat $err_txt
#  exit 1
#fi

cd $HOME\Downloads
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=player_monoids.zip
MTMOD_UNZ_NAME=player_monoids-master
MTMOD_DEST_NAME=player_monoids
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm $MTMOD_SRC_ZIP
fi
wget https://github.com/minetest-mods/player_monoids/archive/master.zip
mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi


cd "$HOME/Downloads"
MTMOD_DL_ZIP=master
MTMOD_SRC_ZIP=worldedit.zip
MTMOD_UNZ_NAME=Uberi-Minetest-WorldEdit-*
MTMOD_DEST_NAME=worldedit
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
echo "Installing sfan5's  <https://forum.minetest.net/viewtopic.php?t=572>"
echo "Installing sfan5's  <https://forum.minetest.net/viewtopic.php?t=572>" >> $MTMOD_SRC_ZIP.txt
if [ -f $MTMOD_DL_ZIP ]; then
  rm $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm $MTMOD_SRC_ZIP
fi
rm -Rvf $MTMOD_UNZ_NAME
wget https://github.com/Uberi/MineTest-WorldEdit/zipball/master
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv -f $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi


cd "$HOME/Downloads"
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=u_skins.zip
MTMOD_UNZ_NAME=minetest-u_skinsdb-master
MTMOD_DEST_NAME=u_skins
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
rm -Rvf $MTMOD_UNZ_NAME
# NOTE: a skin database is at http://minetest.fensta.bplaced.net/
# bell07's 2016 (FORK of Krock's fork of dmonty's) u_skins (u_skins is a skin GUI that works with unified_inventory, whereas other skin GUIs often use inventory++)
# Krock's is outdated and has remaining bugs such as in updater: wget https://github.com/SmallJoker/minetest-u_skinsdb/archive/master.zip
# bell07's no longer exists
# wget https://github.com/bell07/minetest-u_skinsdb/archive/master.zip
wget https://github.com/dmonty2/minetest-u_skinsdb/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv -f $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi

# Update skins database:
#(jq is a json processor, required for the updater bash script:)
sudo apt-get -y install jq
cd "$MTMOD_DEST_PATH"
# cd u_skins  #bell07's version is a mod, not a modpack
cd updater

# Only download entire skins database if you
# REALLY, REALLY MEAN IT:
# ./update_skins_db.sh
# (note, bell07 has the fixed bash script, but the python3 script is still bugged as of 2016-01-29, and the .NET assembly seems to only work for Windows (has meta directory not found error on mono for Linux)


#MarkBu's ambience/ambiance ambient sounds (burli on https://forum.minetest.net/viewtopic.php?f=9&t=14814 )
#cd "$HOME/Downloads"
#MTMOD_DL_ZIP=master.zip
#MTMOD_SRC_ZIP=ambianceplus.zip
#MTMOD_UNZ_NAME=ambianceplus-master
#MTMOD_DEST_NAME=ambianceplus
#MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ -f $MTMOD_DL_ZIP ]; then
#  rm -f $MTMOD_DL_ZIP
#fi
#if [ -f $MTMOD_SRC_ZIP ]; then
#  rm -f $MTMOD_SRC_ZIP
#fi
#rm -Rvf $MTMOD_UNZ_NAME
#wget https://github.com/MarkuBu/ambianceplus/archive/master.zip
##git clone https://github.com/MarkuBu/ambianceplus.git
#mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
#unzip "$MTMOD_SRC_ZIP"
#sudo mv -f $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
#if [ ! -d "$MTMOD_DEST_PATH" ]; then
#  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
#  cat $err_txt
#  exit 1
#fi

#tenplus1's ambience/ambiance ambient sounds (fork linked at original's thread at https://forum.minetest.net/viewtopic.php?f=11&t=2807&start=275 )
cd "$HOME/Downloads"
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=ambience.zip
MTMOD_UNZ_NAME=ambience-master
MTMOD_DEST_NAME=ambience
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
rm -Rvf $MTMOD_UNZ_NAME
wget https://github.com/tenplus1/ambience/archive/master.zip
#git clone https://github.com/tenplus1/ambience.git
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv -f $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi


#expertmm fork of minetest-mod-metatools
cd "$HOME/Downloads"
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=metatools.zip
MTMOD_UNZ_NAME=minetest-mod-metatools-master
MTMOD_DEST_NAME=metatools
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
rm -Rvf $MTMOD_UNZ_NAME
wget https://github.com/expertmm/minetest-mod-metatools/archive/master.zip
#git clone https://github.com/expertmm/minetest-mod-metatools.git
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv -f $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi


#[mod-pack] sky critters (for mobs_redo) [mobs_sky] <https://forum.minetest.net/viewtopic.php?f=9&t=12688>
#requires mobs redo
cd $HOME/Downloads
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=mobs_sky.zip
MTMOD_UNZ_NAME=mobs_sky-master
MTMOD_DEST_NAME=mobs_sky
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
wget https://github.com/blert2112/mobs_sky/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi

#requires xpanes (now part of minetest_game), fake_fire (or not, since only uses fire:flint_and_steel, and fire is in minetest_game), and mobs redo or creatures
#REPLACES pyramids
cd $HOME/Downloads
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=spawners.zip
MTMOD_UNZ_NAME=minetest_gamers-spawners-*
MTMOD_DEST_NAME=spawners
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
wget https://bitbucket.org/minetest_gamers/spawners/get/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
#mv minetest_gamers-spawners-* minetest_gamers-spawners
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi
echo "SPAWN_PYRAMIDS = true" > settings.txt
echo "SPAWNERS_GENERATE = true" >> settings.txt
echo "CHESTS_GENERATE = true" >> settings.txt
sudo mv settings.txt "$MTMOD_DEST_PATH/"
echo "NOTE: in spawners, only SPAWNERS_GENERATE or CHESTS_GENERATE, not both (SPAWNERS_GENERATE overrides) spawn in world for now. See thread for updated info: https://forum.minetest.net/viewtopic.php?f=11&t=13857&start=25"
echo "see also expertmm's game-install-enliven-testing-SPAWNERS_BOTH_DEBUG.txt"


#REPLACES PilzAdam's, modified by kaeza, maintained by VenessaE; FORMERLY in homedecor_modpack
#forum post: https://forum.minetest.net/viewtopic.php?t=13762
cd $HOME/Downloads
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=signs_lib.zip
MTMOD_UNZ_NAME=signs_lib-master
MTMOD_DEST_NAME=signs_lib
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
wget https://github.com/minetest-mods/signs_lib/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi



#cd $HOME/Downloads
#MTMOD_DL_ZIP=master.zip
#MTMOD_SRC_ZIP=minetest-signs_lib-extrafonts.zip
#MTMOD_UNZ_NAME=minetest-signs_lib-extrafonts-master
#MTMOD_DEST_NAME=signs_lib/textures
#MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
##if [ -d "$MTMOD_UNZ_NAME" ]; then
#rm -Rf $MTMOD_UNZ_NAME
##fi
#if [ -f $MTMOD_DL_ZIP ]; then
#  rm -f $MTMOD_DL_ZIP
#fi
#if [ -f $MTMOD_SRC_ZIP ]; then
#  rm -f $MTMOD_SRC_ZIP
#fi
#if [ -d "$MTMOD_DEST_PATH" ]; then
#  sudo rm -Rf "$MTMOD_DEST_PATH"
#fi
#wget https://github.com/kaeza/minetest-signs_lib-extrafonts/archive/master.zip
#mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
#unzip "$MTMOD_SRC_ZIP"
##sudo cp -f $MTMOD_UNZ_NAME/15px/* "$MTMOD_DEST_PATH/"
#sudo cp -f $MTMOD_UNZ_NAME/31px/* "$MTMOD_DEST_PATH/"
#if [ ! -d "$MTMOD_DEST_PATH" ]; then
#  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
#  cat $err_txt
#  exit 1
#fi



cd $HOME/Downloads
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=playeranim.zip
MTMOD_UNZ_NAME=playeranim-master
MTMOD_DEST_NAME=playeranim
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
wget https://github.com/minetest-mods/playeranim/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi

cd $HOME/Downloads
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=homedecor_modpack.zip
MTMOD_UNZ_NAME=homedecor_modpack-master
MTMOD_DEST_NAME=homedecor_modpack
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
wget https://github.com/minetest-mods/homedecor_modpack/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi


#a rather non-maintained mod--forum link is at https://forum.minetest.net/viewtopic.php?id=3663
cd $HOME/Downloads
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=birthstones.zip
#MTMOD_UNZ_NAME=birthstones-mod-master
MTMOD_UNZ_NAME=minetest-birthstones-master
MTMOD_DEST_NAME=birthstones
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
#wget https://github.com/Doc22/birthstones-mod/archive/master.zip
wget https://github.com/expertmm/birthstones-mod/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo rm -Rf "$MTMOD_DEST_PATH"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi



cd $HOME/Downloads
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=bakedclay.zip
MTMOD_UNZ_NAME=bakedclay-master
MTMOD_DEST_NAME=bakedclay
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
wget https://github.com/tenplus1/bakedclay/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi

cd $HOME/Downloads
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=farming.zip
MTMOD_UNZ_NAME=farming-master
MTMOD_DEST_NAME=farming
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
wget https://github.com/tenplus1/farming/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi


#Forum post: https://forum.minetest.net/viewtopic.php?f=11&t=10423
#Wuzzy's slimenodes mod (only available via give).
cd "$HOME/Downloads"
#MTMOD_DL_ZIP=master.zip
#MTMOD_SRC_ZIP=slimenodes.zip
#MTMOD_UNZ_NAME=slimenodes-master
MTMOD_UNZ_NAME=minetest_slimenodes
MTMOD_DEST_NAME=slimenodes
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
# web view: http://repo.or.cz/w/minetest_slimenodes.git
git clone git://repo.or.cz/minetest_slimenodes.git
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi


# https://forum.minetest.net/viewtopic.php?f=11&t=12440&p=310915#p310915
cd $HOME/Downloads
#MTMOD_DL_ZIP=file.php?id=6140
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=invhack.zip
MTMOD_UNZ_NAME=minetest-invhack-master
MTMOD_DEST_NAME=invhack
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
# wget https://forum.minetest.net/download/file.php?id=6140
# forum link changed, so use salahzar's GitHub upload instead:
wget https://github.com/salahzar/minetest-invhack/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi



cd $HOME/Downloads
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=unifieddyes.zip
MTMOD_UNZ_NAME=unifieddyes-master
MTMOD_DEST_NAME=unifieddyes
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
wget https://github.com/minetest-mods/unifieddyes/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi


#(a trmp is just a modpack of TRMs for treasurer. At least one trm must be installed for treasurer to to anything)
cd $HOME/Downloads
MTMOD_DL_ZIP=file.php?id=1301
MTMOD_SRC_ZIP=trmp_minetest_game.zip
MTMOD_UNZ_NAME=trmp_minetest_game
MTMOD_DEST_NAME=trmp_minetest_game
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
wget https://forum.minetest.net/download/file.php?id=1301
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi

#Sokomine's original version has no security ( https://forum.minetest.net/viewtopic.php?id=4877 )
cd $HOME/Downloads
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=travelnet.zip
MTMOD_UNZ_NAME=travelnet-master
MTMOD_DEST_NAME=travelnet
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ -d "$MTMOD_UNZ_NAME" ]; then
rm -Rf $MTMOD_UNZ_NAME
#fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
#wget https://github.com/Sokomine/travelnet/archive/master.zip
wget https://github.com/expertmm/travelnet/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
sudo rm -Rf "$MTMOD_DEST_PATH/etc"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  exit 1
fi
echo
echo
echo
echo
echo "# remove not available on 0.4.16 stable (is only avail on 0.4.16-dev or higher)"
echo "sudo rm -Rf /usr/share/games/minetest/games/ENLIVEN/mods/worldedit/worldedit_brush"
echo "# optionally:"
echo "sudo cp -R ~/GitHub/EnlivenMinetest/etc/Mods\,WIP/* $MT_MYGAME_MODS_PATH/"
echo "# not recommended:"
echo "sudo cp -R ~/GitHub/EnlivenMinetest/etc/Mods\,stopgap/* $MT_MYGAME_MODS_PATH/"
echo "sudo rm -Rf $MT_MYGAME_MODS_PATH/1.nonworking"


echo ""
echo ""
echo ""
echo "#### $MT_MYWORLD_DIR/world.mt: ####"
cat "$MT_MYWORLD_DIR/world.mt"
echo "### end $MT_MYWORLD_DIR/world.mt ##"
echo ""
echo ""
echo ""
#echo "Remember, if you are using Better HUD + Hunger, add the values for the new meat to hunger.lua"
#echo "--see <https://forum.minetest.net/viewtopic.php?f=11&t=9917&hilit=mobs>"
echo "NOTE: hud_hunger/hunger/food.lua now comes with values for food from mobs."
#hud_hunger now includes mobs food (see /usr/local/share/minetest/games/enliven/mods/hud_hunger/hunger/food.lua )
echo ""
echo "NOW MAKE SURE YOU EDIT $MT_MYGAME_MODS_PATH/protector/init.lua near line 325 to block comment ( --[[ then afterward --]]) the on_rightclick registration (since protection block right-clicked by its owner crashes server)"
echo "Then make sure you login, REMEMBERING to put a password in second box, then logout then:"
echo "  nano $MT_MYWORLD_DIR/players/username where username is YOUR username, give yourself the following permissions to edit areas, edit protector blocks (and other protector nodes), and do other things: areas,delprotect,home,noclip,fly,rollback,settime,teleport,bring,fast,password,give,ban,privs,kick,worldedit"
echo "  bring: allows to you teleport other players"
echo "  ban: allows /ban ip and /unban ip (and /whitelist add player and /whitelist remove player commands if whitelist mod is installed)"
echo "  kick: allows /kick player"
echo "  privs: allows grant and revoke commands"
echo "  delprotect: circumvents protector blocks, including allowing removing them"
echo ""
echo "Also remember to:"
echo "  nano $MT_MYGAME_MODS_PATH/teleporter/config.lua"
echo "  #then change:"
echo "  teleporter.requires_pairing = true"
echo "  # also see other lines in this script that wouldn't echo as non-root"
echo "  #otherwise people can type any coordinates for destination (approaching infinite distance)!"
echo "  * uncomment columns in lapis mod"
echo "  * set number = 0 or number = {min=0, max=0} in cme since only using cme for creatures:*_spawner nodes and for compatibility with old worlds"
echo "  * remember to /grant yourself invhack and then /giveme invhack:tool for editing player inventories as moderator"
echo "  * Make sure client (server done already above) minetest.conf has secure.trusted_mods = advanced_npc"
echo "  * Make sure writable minetest conf was successfully written"
echo "  over /usr/local/share/minetest/games/enliven/minetest.conf with:"
echo "protector_radius = 7"
echo "protector_pvp = true"
echo "protector_pvp_spawn = 10"
echo "protector_drop = true"
echo "protector_hurt = 1"
echo ""
echo "default_privs = interact,shout,home"
echo "max_users = 50"
echo "motd = \"Actions and chat messages are logged. Visit fcacloud.com/minetest for recipes and live map.\""
echo "disallow_empty_passwords = true"
echo ""
echo "#not all settings can be changed in this minetest.conf (see minetest.conf.example in THIS folder)"
echo "#some settings can only be changed in client's local copy of minetest.conf (see or login scripts in network)"

