#!/bin/sh
# Copyright 2017 expertmm. License:
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

#First make sure all folders in $HOME/.minetest are created (I am not sure whether this is required!):
# minetestserver
# Mods were found at https://forum.minetest.net/viewforum.php?f=11


# * Git version uses /home/*/minetest/games and /usr/local/share/minetest/games but the latter is used for minetestserver (minetest-server package)


# (Ubuntu 14.04 Trusty Tahr Server) folders were found using:
# cd /
# sudo find -name 'worlds' (worlds folder is in $HOME/.minetest)
# sudo find -name 'minimal' (stable build [such as 0.4.9 games folder is /usr/share/games/minetest/games, but git version games folder is /usr/local/share/minetest/games)





#region paste this part into terminal to get some great environment variables
if [ "$0" = "-bash" ]; then
  echo "you must have pasted this into terminal, so assuming REPO_PATH"
  REPO_PATH="$HOME/GitHub/EnlivenMinetest"
  echo "$REPO_PATH"
else
  SCRIPT=$(readlink -f "$0")
  # Absolute path this script is in, thus /home/user/bin
  SCRIPTPATH=$(dirname "$SCRIPT")
  REPO_PATH=$(dirname "$SCRIPTPATH")
fi

PATCHES_PATH="$REPO_PATH/patches"

if [ ! -d "$PATCHES_PATH" ]; then
  # maybe moved somewhere or this code was pasted
  PATCHES_PATH=$HOME/GitHub/EnlivenMinetest/patches
fi
if [ ! -d "$PATCHES_PATH" ]; then
  # maybe running from root of repo
  PATCHES_PATH="patches"
fi
if [ ! -d "$PATCHES_PATH" ]; then
  # should work if ran from folder where exists
  PATCHES_PATH="../patches"
fi
if [ ! -d "$PATCHES_PATH" ]; then
  echo "ERROR: could not find patches such as in $PATCHES_PATH"
  sleep 3
  exit 1
fi
# NOTE: minetest mods (other than 0.4.16 client-side mods) are ALWAYS ONLY installed on server, unless you need them for singleplayer
mtgame_name="minetest_game"
USR_SHARE_MINETEST=/usr/share/games/minetest
try_path="/usr/share/minetest"
if [ -d "$try_path" ]; then
  # Arch linux
  USR_SHARE_MINETEST="$try_path"
fi
if [ ! -d "$USR_SHARE_MINETEST" ]; then
  # IF git version is installed and regular one is NOT:
  try_path="/usr/local/share/minetest"
  if [ -d "$try_path" ]; then
    USR_SHARE_MINETEST="$try_path"
  fi
fi
# UNUSED (unknown use): MT_GAMES_DIR=$HOME/.minetest/mods
# intentionally skip the slash in the following line since $USR_SHARE_MINETEST already starts with one:
MT_BACKUP_GAMES_DIR=$HOME/Backup$USR_SHARE_MINETEST/games
MT_GAMES_DIR=$USR_SHARE_MINETEST/games
MT_MYGAME_BAK=$USR_SHARE_MINETEST/ENLIVEN_BAK
MT_MYGAME_NAME=ENLIVEN
MT_MYGAME_DIR=$MT_GAMES_DIR/$MT_MYGAME_NAME
# formerly MT_MYGAME_MODDIR:
MT_MYGAME_MODS_PATH=$MT_MYGAME_DIR/mods
MT_MYWORLD_NAME=FCAGameAWorld
MT_MYWORLD_DIR=$HOME/.minetest/worlds/$MT_MYWORLD_NAME
err_txt=$HOME/err-enliven.txt
# see also https://www.shellscript.sh/functions.html

add_zipped_mod()
{
  cd $HOME/Downloads
  MTMOD_DEST_NAME=$1
  MTMOD_UNZ_NAME=$2
  URL=$3
  MTMOD_SRC_ZIP=$MTMOD_DEST_NAME.zip
  MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
  if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
    rm -Rf $MTMOD_UNZ_NAME
  fi
  if [ -f $MTMOD_SRC_ZIP ]; then
    rm -f $MTMOD_SRC_ZIP
  fi
  if [ -d "$MTMOD_DEST_PATH" ]; then
    sudo rm -Rf "$MTMOD_DEST_PATH"
  fi
  wget -O $MTMOD_SRC_ZIP $URL
  unzip "$MTMOD_SRC_ZIP"
  sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
  sudo rm -Rf "$MTMOD_DEST_PATH/etc"
  if [ ! -d "$MTMOD_DEST_PATH" ]; then
    echo "  ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
    cat $err_txt
    sleep 3
    exit 1
  else
    echo "  added as $MTMOD_DEST_PATH"
  fi
}

add_git_clone_mod()
{
  cd $HOME/Downloads
  MTMOD_DEST_NAME=$1
  MTMOD_UNZ_NAME=$2
  URL=$3
  MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
  if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
    rm -Rf $MTMOD_UNZ_NAME
  fi
  if [ -d "$MTMOD_DEST_PATH" ]; then
    sudo rm -Rf "$MTMOD_DEST_PATH"
  fi
  git clone $URL
  sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
  sudo rm -Rf "$MTMOD_DEST_PATH/etc"
  if [ ! -d "$MTMOD_DEST_PATH" ]; then
    echo "  ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
    cat $err_txt
    sleep 3
    exit 1
  else
    echo "  added as $MTMOD_DEST_PATH"
  fi
}

remove_mod()
{
  cd $HOME/Downloads
  MTMOD_DEST_NAME=$1
  MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
  if [ -d "$MTMOD_DEST_PATH" ]; then
    sudo rm -Rf "$MTMOD_DEST_PATH"
  fi
  if [ -d "$MTMOD_DEST_PATH" ]; then
    echo "  ERROR in remove_mod: failed to remove $MTMOD_DEST_PATH, so cannot continue." > $err_txt
    cat $err_txt
    sleep 3
    exit 1
  else
    echo "  removed $MTMOD_DEST_PATH"
  fi
}

#endregion paste this part into terminal to get some great environment variables





# BACKUP THE WORLD:
sudo chown $USER "$MT_MYWORLD_DIR/world.mt"
sudo chown $USER "$MT_MYWORLD_DIR/world.mt.1st"
if [ ! -d "$MT_MYGAME_DIR" ]; then
  sudo mkdir "$MT_MYGAME_DIR"
fi
if [ -f "$MT_MYWORLD_DIR/world.mt.1st" ]; then
  echo "Already backed up world.mt to $MT_MYWORLD_DIR/world.mt.1st"
else
  cp "$MT_MYWORLD_DIR/world.mt" "$MT_MYWORLD_DIR/world.mt.1st"
  echo "The original world.mt is now backed up at $MT_MYWORLD_DIR/world.mt.1st"
fi
touch "$MT_MYWORLD_DIR/world.mt"
mv -f "$MT_MYWORLD_DIR/world.mt" "$MT_MYWORLD_DIR/world.mt.bak"

# REMAKE world.mt
cd
echo "gameid = $MT_MYGAME_NAME" > "world.mt"
sudo mv "world.mt" "$MT_MYWORLD_DIR/world.mt"
sudo chown $USER "$MT_MYWORLD_DIR/world.mt"
sudo chgrp $USER "$MT_MYWORLD_DIR/world.mt"
echo "backend = leveldb" >> "$MT_MYWORLD_DIR/world.mt"
#mv "world.mt" $MT_MYWORLD_DIR/world.mt

#MT_MYGAME_DIR (a Minetest "game") is the equivalent of a Minecraft modpack, however, in this case it is actually a collection of mods and modpacks, either of which can be in the mods folder

#cd
if [ ! -d "$HOME/Downloads" ]; then
  mkdir "$HOME/Downloads"
fi
cd "$HOME/Downloads"

if [ -d "$MT_MYGAME_BAK" ];
then
  echo "already backed up to $MT_MYGAME_BAK"
else
  sudo mv "$MT_MYGAME_DIR" "$MT_MYGAME_BAK"
  sudo mkdir "$MT_MYGAME_DIR"
fi


#sudo mkdir "$MT_MYGAME_DIR"
#sudo mkdir "$MT_MYGAME_MODS_PATH"
if [ ! -d "$MT_MYGAME_DIR/" ]; then
  echo "ERROR: failed to create $MT_MYGAME_DIR, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi
#sudo cp -R $USR_SHARE_MINETEST/games/$mtgame_name/mods/* "$MT_MYGAME_DIR/mods/"
if [ -d "$USR_SHARE_MINETEST/games/minetest" ]; then
  # Arch linux
  mtgame_name="minetest"
fi
sudo cp -R $USR_SHARE_MINETEST/games/$mtgame_name/* "$MT_MYGAME_DIR/"

#wget https://github.com/BlockMen/cme/releases/download/v2.3/cme-2_3-BlockMen.zip
#unzip cme-2_3-BlockMen.zip
#sudo mv cme "$MT_MYGAME_MODS_PATH/cme"
##DO NOT DO THIS (since cme is a modpack): echo "load_mod_cme = true" >> "$MT_MYWORLD_DIR/world.mt"
#echo "#cme Creatures MOB-Engine (cme) is a modpack" >> "$MT_MYWORLD_DIR/world.mt"

cd "$HOME/Downloads"
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=mobs_redo.zip
MTMOD_UNZ_NAME=mobs_redo-master
MTMOD_DEST_NAME=mobs
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
rm -Rvf $MTMOD_UNZ_NAME
#sudo rm -Rvf "$MTMOD_DEST_PATH"
echo "Installing TenPlus1's mobs.zip from https://github.com/tenplus1/mobs_redo/archive/master.zip"
echo "Installing TenPlus1's mobs.zip from https://github.com/tenplus1/mobs_redo/archive/master.zip" > mobs.zip.txt
#SEE ALSO RELEASE VERSION (must be logged in to download): https://forum.minetest.net/download/file.php?id=5282
#wget https://github.com/tenplus1/mobs/archive/master.zip
wget https://github.com/tenplus1/mobs_redo/archive/master.zip
mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi
echo "load_mod_mobs = true" >> "$MT_MYWORLD_DIR/world.mt"




cd "$HOME/Downloads"
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=mobs_monster.zip
MTMOD_UNZ_NAME=mobs_monster-master
MTMOD_DEST_NAME=mobs_monster
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
rm -Rvf $MTMOD_UNZ_NAME
wget https://github.com/tenplus1/mobs_monster/archive/master.zip
mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi
echo "load_mod_mobs_monster = true" >> "$MT_MYWORLD_DIR/world.mt"

cd "$HOME/Downloads"
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=mobs_animal.zip
MTMOD_UNZ_NAME=mobs_animal-master
MTMOD_DEST_NAME=mobs_animal
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
rm -Rvf $MTMOD_UNZ_NAME
wget https://github.com/tenplus1/mobs_animal/archive/master.zip
mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi
echo "load_mod_mobs_animal = true" >> "$MT_MYWORLD_DIR/world.mt"



#the following downloads protector (REDO version posted at https://forum.minetest.net/viewtopic.php?f=11&t=9376) not the original 2012 protector or 2012 fork of 2012 protector
#rm protector.zip
#wget https://forum.minetest.net/download/file.php?id=5046
#mv -f "file.php?id=5046" protector.zip
#USE GIT VERSION INSTEAD:
cd "$HOME/Downloads"
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=protector.zip
MTMOD_UNZ_NAME=protector-master
MTMOD_DEST_NAME=protector
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
rm -Rvf $MTMOD_UNZ_NAME
#as of 2016-02-20, CRASHES on default 0.4.9 minetesterver 0.4.13 git 2016-02-20:
wget https://github.com/tenplus1/protector/archive/master.zip
#expertmm fork to work in above situation:
#wget https://github.com/expertmm/protector/archive/master.zip
#results in UNKNOWN NODE for all protected blocks: wget https://github.com/MinetestForFun/protector/archive/master.zip
mv -f $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
#sudo rm -Rf "$MT_MYGAME_MODS_PATH/protector-master"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi

#sudo su -
#WRITEABLE_MINETEST_CONF=$USR_SHARE_MINETEST/games/$MT_MYGAME_NAME/minetest.conf
WRITEABLE_MINETEST_CONF=$HOME/minetest.conf
rm -f "$HOME/minetest.conf"
if [ ! -f "$USR_SHARE_MINETEST/games/$MT_MYGAME_NAME/minetest.conf" ]; then
  sudo cp "$USR_SHARE_MINETEST/games/$mtgame_name/minetest.conf" "$USR_SHARE_MINETEST/games/$MT_MYGAME_NAME/minetest.conf.1st"
fi
cp "$USR_SHARE_MINETEST/games/$mtgame_name/minetest.conf" "$WRITEABLE_MINETEST_CONF"
touch "$WRITEABLE_MINETEST_CONF"
#4080 since boundaries in chunkymap/singleimage.py (to be compatible with approximate browser max image size) are -4096 to 4096
echo "map_generation_limit = 4096" >> "$WRITEABLE_MINETEST_CONF"
#NOTE: map_generation_limit (aka world boundary, world border, or world limit) must be divisible by 64, so for example, 5000 results in invisible wall at 4928
echo "protector_radius = 7" >> "$WRITEABLE_MINETEST_CONF"
echo "protector_flip = true" >> "$WRITEABLE_MINETEST_CONF"
echo "protector_pvp = true" >> "$WRITEABLE_MINETEST_CONF"
echo "protector_pvp_spawn = 10" >> "$WRITEABLE_MINETEST_CONF"
echo "protector_drop = false" >> "$WRITEABLE_MINETEST_CONF"
echo "protector_hurt = 3" >> "$WRITEABLE_MINETEST_CONF"
echo "default_privs = interact,shout,home" >> "$WRITEABLE_MINETEST_CONF"
echo "max_users = 50" >> "$WRITEABLE_MINETEST_CONF"
echo "motd = \"Actions and chat messages are logged. Use inventory to see recipes (use web for live map if available).\""  >> "$WRITEABLE_MINETEST_CONF"
echo "disallow_empty_passwords = true" >> "$WRITEABLE_MINETEST_CONF"
echo "secure.trusted_mods = advanced_npc" >> "$WRITEABLE_MINETEST_CONF"
echo "server_dedicated = false" >> "$WRITEABLE_MINETEST_CONF"
echo "hudbars_bar_type = statbar_modern" >> "$WRITEABLE_MINETEST_CONF"
sudo mv -f $HOME/minetest.conf "$USR_SHARE_MINETEST/games/$MT_MYGAME_NAME/minetest.conf"
echo "load_mod_protector = true" >> $MT_MYWORLD_DIR/world.mt


cd "$HOME/Downloads"
#MTMOD_DL_ZIP=master.tar.gz
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=xban2.zip
#MTMOD_UNZ_NAME=minetest-xban2-master
MTMOD_UNZ_NAME=xban2-master
MTMOD_DEST_NAME=xban2
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
rm -Rvf $MTMOD_UNZ_NAME
#wget https://github.com/kaeza/minetest-xban2/archive/master.tar.gz
wget https://github.com/minetest-mods/xban2/archive/master.zip
mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
#tar -xzvf $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
# As http://wiki.minetest.net/Installing_Mods specifies, a mod MUST be renamed to official name as in the official thread of the mod:
mv $MTMOD_UNZ_NAME $MTMOD_DEST_NAME
sudo mv $MTMOD_DEST_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi

echo "load_mod_xban2 = true" >> "$MT_MYWORLD_DIR/world.mt"

cd "$HOME/Downloads"
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=areas.zip
MTMOD_UNZ_NAME=areas-master
MTMOD_DEST_NAME=areas
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
echo "Installing ShadowNinja's <https://forum.minetest.net/viewtopic.php?t=7239>"
echo "Installing ShadowNinja's <https://forum.minetest.net/viewtopic.php?t=7239>" >> $MTMOD_SRC_ZIP.txt
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
rm -Rvf $MTMOD_UNZ_NAME
wget https://github.com/ShadowNinja/areas/archive/master.zip
mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi
echo "load_mod_areas = true" >> "$MT_MYWORLD_DIR/world.mt"

if [ -f "$MT_MYGAME_DIR/game.conf.1st" ]; then
  echo "Already backed up $MT_MYGAME_DIR/game.conf to $MT_MYGAME_DIR/game.conf.1st"
else
  sudo cp "$MT_MYGAME_DIR/game.conf" "$MT_MYGAME_DIR/game.conf.1st"
fi
echo "name = $MT_MYGAME_NAME" > "$HOME/game.conf"
sudo mv -f "$HOME/game.conf" "$MT_MYGAME_DIR/game.conf"
#su -
#FAILS: echo "name = $MT_MYGAME_NAME" > "$MT_MYGAME_DIR/game.conf"
#sudo nano "$MT_MYGAME_DIR/game.conf"
echo ""
echo "You should see $MT_MYGAME_NAME in the list below if the game was configured properly:"
minetestserver --gameid list
echo ""


#ls "$MT_MYGAME_MODS_PATH"
if [ ! -d "$MT_BACKUP_GAMES_DIR" ]; then
  mkdir -p "$MT_BACKUP_GAMES_DIR"
#-p to make parent recursively
fi
first_suffix="_1st"
if [ -d "$MT_BACKUP_GAMES_DIR/$mtgame_name$first_suffix" ]; then
  echo "already backed up $USR_SHARE_MINETEST/games/$mtgame_name"
else
  sudo cp -R "$USR_SHARE_MINETEST/games/$mtgame_name" "$MT_BACKUP_GAMES_DIR/"
fi
#sudo mv "$USR_SHARE_MINETEST/games/fca-game-a" "$USR_SHARE_MINETEST/games/$mtgame_name"

#UNUSED, and is based on a much older version of minetest_game:
#MTMOD_DL_ZIP=master.zip
#MTMOD_SRC_ZIP=carbone-ng.zip
#MTMOD_UNZ_NAME=carbone-ng-master
#MTMOD_DEST_NAME=carbone-ng
##MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#MTMOD_DEST_PATH=$MT_GAMES_DIR/$MTMOD_DEST_NAME
#if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
#  rm -Rf $MTMOD_UNZ_NAME
#fi
#if [ -f "$MTMOD_DL_ZIP" ]; then
#  rm -f "$MTMOD_DL_ZIP"
#fi
#if [ -f "$MTMOD_SRC_ZIP" ]; then
#  rm -f "$MTMOD_SRC_ZIP"
#fi
#cd "$HOME/Downloads"
#wget https://github.com/Calinou/carbone-ng/archive/master.zip
#mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
#unzip $MTMOD_SRC_ZIP
#sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
#if [ ! -d "$MTMOD_DEST_PATH" ]; then
#  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
#  cat $err_txt
#  sleep 3
#  exit 1
#fi

#sudo cp -R /usr/share/games/minetest/games/carbone-ng /usr/local/share/minetest/games/carbone-ng

#IF git version is installed:
#if [ -d "/usr/local/share/minetest/games" ];
#then
#sudo cp -R $USR_SHARE_MINETEST/games/$MT_MYGAME_NAME /usr/local/share/minetest/games/$MT_MYGAME_NAME
#sudo mv $HOME/Downloads/cme /usr/local/share/minetest/games/$MT_MYGAME_NAME/mods/cme
#sudo mv $HOME/Downloads/protector /usr/local/share/minetest/games/$MT_MYGAME_NAME/mods/protector
#fi

# actually farming REDO as per https://forum.minetest.net/viewtopic.php?f=11&t=9019
#wget https://forum.minetest.net/download/file.php?id=5045
#mv "file.php?id=5045" farming.zip
#unzip farming.zip
#sudo rm -Rf $MT_MYGAME_MODS_PATH/farming
#sudo mv farming $MT_MYGAME_MODS_PATH/farming
# breaks 0.4.13 dev version 2016-02-17 (says height_max deprecated, use y_max; and later
#2016-02-17 11:10:19: ERROR[Main]: ModError: Failed to load and run script from $USR_SHARE_MINETEST/games/enliven/mods/farming/init.lua:
#2016-02-17 11:10:19: ERROR[Main]: ...share/minetest/games/enliven/mods/farming/pumpkin.lua:78: attempt to perform arithmetic on field 'LIGHT_MAX' (a nil value)
#2016-02-17 11:10:19: ERROR[Main]: stack traceback:
#2016-02-17 11:10:19: ERROR[Main]:       ...share/minetest/games/enliven/mods/farming/pumpkin.lua:78: in main chunk
#2016-02-17 11:10:19: ERROR[Main]:       [C]: in function 'dofile'
#2016-02-17 11:10:19: ERROR[Main]:       ...al/share/minetest/games/enliven/mods/farming/init.lua:65: in main chunk
# Remove & overwrite Farming REDO since it crashes 0.4.13 git 2016-02-16:
#sudo rm -Rf $MT_MYGAME_MODS_PATH/farming
#sudo cp -R $USR_SHARE_MINETEST/games/$mtgame_name/mods/farming $MT_MYGAME_MODS_PATH/farming

# MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=unified_inventory.zip
MTMOD_UNZ_NAME=unified_inventory-master
MTMOD_DEST_NAME=unified_inventory
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf $MTMOD_UNZ_NAME
fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
# wget -O $MTMOD_SRC_ZIP https://github.com/minetest-technic/unified_inventory/archive/master.zip
# (link above forewards to minetest-mods now)
wget -O $MTMOD_SRC_ZIP https://github.com/minetest-mods/unified_inventory/archive/master.zip
# mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi
echo "load_mod_unified_inventory = true" >> $MT_MYWORLD_DIR/world.mt


MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=technic.zip
MTMOD_UNZ_NAME=technic-master
MTMOD_DEST_NAME=technic
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf $MTMOD_UNZ_NAME
fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
#wget https://github.com/minetest-technic/technic/archive/master.zip
wget https://github.com/minetest-mods/technic/archive/master.zip
mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi
echo "load_mod_technic = true" >> $MT_MYWORLD_DIR/world.mt



#uninstall:
#if [ -d "$MT_MYGAME_MODS_PATH/unified_inventory" ]; then
#  if [ -d "$HOME/Backup/unified_inventory" ]; then
#    rm -Rf "$HOME/Backup/unified_inventory"
#  fi
#  sudo mv "$MT_MYGAME_MODS_PATH/unified_inventory" "$HOME/Backup/unified_inventory"
#fi
#reinstall:
#sudo mv "$HOME/Backup/unified_inventory" "$MT_MYGAME_MODS_PATH/unified_inventory"

MTMOD_DL_ZIP=treasurer0.2.0.zip
MTMOD_SRC_ZIP=treasurer0.2.0.zip
MTMOD_UNZ_NAME=treasurer
MTMOD_DEST_NAME=treasurer
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -f "tsm_gift_example" ]; then
  rm "tsm_gift_example"
fi
if [ -d "tsm_gift_example" ]; then
  rm -Rf "tsm_gift_example"
fi
if [ -d "tsm_chests_example" ]; then
  rm -Rf "tsm_chests_example"
fi
if [ -d "trm_default_example" ]; then
  rm -Rf "trm_default_example"
fi
if [ -d "tsm_default_example" ]; then
  rm -Rf "tsm_default_example"
fi
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf $MTMOD_UNZ_NAME
fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
wget http://axlemedia.net/abiyahh/users/Wuzzy/downloads/treasurer0.2.0.zip
unzip $MTMOD_SRC_ZIP
sudo mv -f $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi
echo "load_mod_treasurer = true" >> $MT_MYWORLD_DIR/world.mt


#DEPRECATED, replaced by spawners (which includes pyramids worldgen mod)
#MTMOD_DL_ZIP=ebf839579197053b2ead85072757f23158960319.zip
#MTMOD_SRC_ZIP=tsm_pyramids.zip
#MTMOD_UNZ_NAME=tsm_pyramids-*
#MTMOD_DEST_NAME=tsm_pyramids
#MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
#  rm -Rf $MTMOD_UNZ_NAME
#fi
#if [ -f "$MTMOD_DL_ZIP" ]; then
#  rm -f "$MTMOD_DL_ZIP"
#fi
#if [ -f "$MTMOD_SRC_ZIP" ]; then
#  rm -f "$MTMOD_SRC_ZIP"
#fi
#wget http://repo.or.cz/w/minetest_pyramids/tsm_pyramids.git/snapshot/ebf839579197053b2ead85072757f23158960319.zip
#mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
#unzip $MTMOD_SRC_ZIP
#sudo mv -f $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
#if [ ! -d "$MTMOD_DEST_PATH" ]; then
#  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
#  cat $err_txt
#  sleep 3
#  exit 1
#fi

#an old version of worldedit included in a minetest fork last updated 2016:
#MTMOD_DL_ZIP=akiba-*
#wget http://git.akiba.fr:81/minetest/akiba/repository/archive.zip?ref=af571404a27a2cb06842c644930344f565a0b786
#rm -f $MTMOD_DL_ZIP


cd "$HOME/Downloads"
MTMOD_DEST_NAME=trm_pyramids
MTMOD_UNZ_NAME=trm_pyramids
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf "$MTMOD_UNZ_NAME"
fi
mkdir "$MTMOD_UNZ_NAME"
cd "$MTMOD_UNZ_NAME"
wget https://github.com/MinetestForFun/server-minetestforfun/raw/master/mods/trm_pyramids/depends.txt
wget https://github.com/MinetestForFun/server-minetestforfun/raw/master/mods/trm_pyramids/init.lua
wget https://github.com/MinetestForFun/server-minetestforfun/raw/master/mods/trm_pyramids/more_trms.lua
wget https://github.com/MinetestForFun/server-minetestforfun/blob/master/LICENSE
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
sudo mkdir "$MTMOD_DEST_PATH"
sudo mv -f depends.txt "$MTMOD_DEST_PATH/"
sudo mv -f init.lua "$MTMOD_DEST_PATH/"
sudo mv -f more_trms.lua "$MTMOD_DEST_PATH/"
sudo mv -f LICENSE "$MTMOD_DEST_PATH/"
cd ..
rmdir "$MTMOD_UNZ_NAME"

#Wuzzy's hudbars (no builtin bars; used by sprint, hbhunger, and hbarmor) https://forum.minetest.net/viewtopic.php?f=11&t=11153&hilit=hunger
cd $HOME/Downloads
#MTMOD_DL_ZIP=master.zip
#MTMOD_SRC_ZIP=hudbars.zip
MTMOD_UNZ_NAME=minetest_hudbars
MTMOD_DEST_NAME=hudbars
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
rm -Rf $MTMOD_UNZ_NAME
fi
#if [ -f $MTMOD_DL_ZIP ]; then
#  rm -f $MTMOD_DL_ZIP
#fi
#if [ -f $MTMOD_SRC_ZIP ]; then
#  rm -f $MTMOD_SRC_ZIP
#fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
git clone git://repo.or.cz/minetest_hudbars.git
#aka http://repo.or.cz/w/minetest_hudbars.git
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi


if [ ! -d "$MT_MYGAME_MODS_PATH/hudbars" ]; then
cd "$HOME/Downloads"
#MTMOD_DL_ZIP=hud_hunger-2_x_1-BlockMen.zip
#MTMOD_SRC_ZIP=hud_hunger-2_x_1-BlockMen.zip
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=hud_hunger.zip
MTMOD_UNZ_NAME=hud_hunger
MTMOD_DEST_NAME=hud_hunger
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#in case someone installed the mods apart from the modpack:
if [ -d "$MT_MYGAME_MODS_PATH/hud" ]; then
  sudo rm -Rf "$MT_MYGAME_MODS_PATH/hud"
fi
if [ -d "$MT_MYGAME_MODS_PATH/hunger" ]; then
  sudo rm -Rf "$MT_MYGAME_MODS_PATH/hunger"
fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
rm -Rvf $MTMOD_UNZ_NAME
#BlockMen's is not maintained, & has problem on hud/buildin line 79 (crash since air can be nil)
#wget https://github.com/BlockMen/hud_hunger/releases/download/2.x.1/hud_hunger-2_x_1-BlockMen.zip
#FozLand's has a couple fixes
#wget https://github.com/FozLand/hud_hunger/archive/master.zip
#tenplus1's fixes nil air, nil player, and sprint
wget https://github.com/tenplus1/hud_hunger/archive/master.zip
unzip $MTMOD_SRC_ZIP
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
sudo rm "$MTMOD_DEST_PATH/hunger/functions_UNUSED_sprint.lua"
sudo mv "$MTMOD_DEST_PATH/hunger/functions.lua" "$MTMOD_DEST_PATH/hunger/functions_UNUSED_sprint.lua"
sudo mv "$MTMOD_DEST_PATH/hunger/functions_(nosprint).lua" "$MTMOD_DEST_PATH/hunger/functions.lua"
sudo rm "$MTMOD_DEST_PATH/hunger/init_UNUSED_sprint.lua"
sudo mv "$MTMOD_DEST_PATH/hunger/init.lua" "$MTMOD_DEST_PATH/hunger/init_UNUSED_sprint.lua"
sudo mv "$MTMOD_DEST_PATH/hunger/init_(nosprint).lua" "$MTMOD_DEST_PATH/hunger/init.lua"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi
# END IF no hudbars mod
else
if [ -d "$MT_MYGAME_MODS_PATH/hud_hunger" ]; then
sudo rm -Rvf "$MT_MYGAME_MODS_PATH/hud_hunger"
fi
fi

#Wuzzy's hbarmor for hudbars https://forum.minetest.net/viewtopic.php?f=11&t=11153&hilit=hunger
cd $HOME/Downloads
#MTMOD_DL_ZIP=master.zip
#MTMOD_SRC_ZIP=hudbars.zip
MTMOD_UNZ_NAME=minetest_hbarmor
MTMOD_DEST_NAME=hbarmor
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf $MTMOD_UNZ_NAME
fi
#if [ -f $MTMOD_DL_ZIP ]; then
#  rm -f $MTMOD_DL_ZIP
#fi
#if [ -f $MTMOD_SRC_ZIP ]; then
#  rm -f $MTMOD_SRC_ZIP
#fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
git clone git://repo.or.cz/minetest_hbarmor.git
#aka http://repo.or.cz/minetest_hbarmor.git/snapshot/bfc5f8cbb560eff6f206eec3242f8401d11c1310.zip
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi

#Wuzzy's hbhunger for hudbars https://forum.minetest.net/viewtopic.php?f=11&t=11153&hilit=hunger
cd $HOME/Downloads
#MTMOD_DL_ZIP=master.zip
#MTMOD_SRC_ZIP=hbhunger.zip
MTMOD_UNZ_NAME=minetest_hbhunger
MTMOD_DEST_NAME=hbhunger
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf $MTMOD_UNZ_NAME
fi
#if [ -f $MTMOD_DL_ZIP ]; then
#  rm -f $MTMOD_DL_ZIP
#fi
#if [ -f $MTMOD_SRC_ZIP ]; then
#  rm -f $MTMOD_SRC_ZIP
#fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
git clone git://repo.or.cz/minetest_hbhunger.git
#aka http://repo.or.cz/minetest_hbhunger.git/snapshot/da70eba4fd0a9644cdb0a5b0d7ee3d93f7e61acf.zip
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi


cd "$HOME/Downloads"
# MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=moreblocks.zip
MTMOD_UNZ_NAME=moreblocks-master
MTMOD_DEST_NAME=moreblocks
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -d "moreblocks-master" ]; then
  rm -Rf moreblocks-master
fi
if [ -f "master.zip" ]; then
  rm master.zip
fi
if [ -f "moreblocks.zip" ]; then
  rm moreblocks.zip
fi
# wget https://gitorious.com/calinou/moreblocks/archive/master.zip
wget -O $MTMOD_SRC_ZIP https://github.com/minetest-mods/moreblocks/archive/master.zip
# mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
sudo mv -f $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi


MTMOD_SRC_ZIP=pipeworks.zip
MTMOD_UNZ_NAME=pipeworks-master
MTMOD_DEST_NAME=pipeworks
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf "$MTMOD_UNZ_NAME"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
#wget -O $MTMOD_SRC_ZIP https://github.com/VanessaE/pipeworks/archive/master.zip
wget -O $MTMOD_SRC_ZIP https://github.com/minetest-mods/pipeworks/archive/master.zip
unzip "$MTMOD_SRC_ZIP"
if [ -d "$MTMOD_DEST_PATH" ]; then
  echo "removing old $MTMOD_DEST_PATH"
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi


MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=plantlife_modpack.zip
MTMOD_UNZ_NAME=plantlife_modpack-master
MTMOD_DEST_NAME=plantlife_modpack
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf "$MTMOD_UNZ_NAME"
fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
wget https://github.com/VanessaE/plantlife_modpack/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi



#NOTE: https://forum.minetest.net/viewtopic.php?f=9&t=12368
# has blocks, but OTHER ONE ONLY HAS DYE (not used): https://forum.minetest.net/viewtopic.php?f=9&t=11287
cd "$HOME/Downloads"
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=lapis_Napiophelios.zip
MTMOD_UNZ_NAME=LapisLazuli-master
MTMOD_DEST_NAME=lapis
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf "$MTMOD_UNZ_NAME"
fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
wget https://github.com/Napiophelios/LapisLazuli/archive/master.zip
mv "$MTMOD_DL_ZIP" "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi

#cd "$HOME/Downloads"
#MTMOD_DL_ZIP=master.zip
#MTMOD_SRC_ZIP=helicopter.zip
#MTMOD_UNZ_NAME=helicopter-master
#MTMOD_DEST_NAME=helicopter
#if [ -f "$MTMOD_DL_ZIP" ]; then
#  rm -f "$MTMOD_DL_ZIP"
#fi
#if [ -f "$MTMOD_SRC_ZIP" ]; then
#  rm -f "$MTMOD_SRC_ZIP"
#fi
#wget https://github.com/SokolovPavel/helicopter/archive/master.zip
#mv "$MTMOD_DL_ZIP" "$MTMOD_SRC_ZIP"
#unzip "$MTMOD_SRC_ZIP"
#sudo mv "$MTMOD_UNZ_NAME" "$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME"
#UNINSTALL since crashes 0.4.13 git 2016-02:
#sudo mv "$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME" "$MTMOD_UNZ_NAME"

MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=biome_lib.zip
MTMOD_UNZ_NAME=biome_lib-master
MTMOD_DEST_NAME=biome_lib
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf "$MTMOD_UNZ_NAME"
fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
wget https://github.com/VanessaE/biome_lib/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi

MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=moretrees.zip
MTMOD_UNZ_NAME=moretrees-master
MTMOD_DEST_NAME=moretrees
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf "$MTMOD_UNZ_NAME"
fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
wget https://github.com/VanessaE/moretrees/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi


MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=minetest-3d_armor.zip
MTMOD_UNZ_NAME=minetest-3d_armor-master
MTMOD_DEST_NAME=3d_armor
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf "$MTMOD_UNZ_NAME"
fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
wget https://github.com/stujones11/minetest-3d_armor/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi
#mv minetest-3d_armor-master minetest-3d_armor_MODPACK
#sudo mv minetest-3d_armor_MODPACK/wieldview $MT_MYGAME_MODS_PATH/wieldview
#sudo mv minetest-3d_armor_MODPACK/3d_armor $MT_MYGAME_MODS_PATH/3d_armor
#sudo mv minetest-3d_armor_MODPACK/shields $MT_MYGAME_MODS_PATH/shields
#echo "load_mod_wieldview = true" >> $MT_MYWORLD_DIR/world.mt
echo "load_mod_3d_armor = true" >> $MT_MYWORLD_DIR/world.mt
#echo "load_mod_shields = true" >> $MT_MYWORLD_DIR/world.mt
#echo "load_mod_technic_armor = false" >> $MT_MYWORLD_DIR/world.mt

cd ~/Downloads
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=caverealms.zip
MTMOD_UNZ_NAME=minetest-caverealms-master
MTMOD_DEST_NAME=caverealms
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf "$MTMOD_UNZ_NAME"
fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
wget https://github.com/HeroOfTheWinds/minetest-caverealms/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi

#if [ -f "master.zip" ]; then
  #rm master.zip
#fi
#wget https://github.com/Splizard/minetest-mod-snow/archive/master.zip
#mv master.zip snow.zip
#unzip snow.zip
#mv minetest-mod-snow-master snow
#sudo mv snow "$MT_MYGAME_MODS_PATH/snow"
# (since snow prevents server 0.4.13 git 2016-02-16 from starting):
#sudo mv $MT_MYGAME_MODS_PATH/snow $HOME/Downloads/snow

MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=moreores.zip
MTMOD_UNZ_NAME=moreores-master
MTMOD_DEST_NAME=moreores
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf "$MTMOD_UNZ_NAME"
fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
wget https://github.com/Calinou/moreores/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi

MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=sprint.zip
MTMOD_UNZ_NAME=sprint-master
MTMOD_DEST_NAME=sprint
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf "$MTMOD_UNZ_NAME"
fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
# sprint https://forum.minetest.net/viewtopic.php?f=9&t=9650
wget https://github.com/GunshipPenguin/sprint/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi

#the following is NOT needed, since one of the mods above adds the home gui and home permission (but no /home or /sethome command)
#if [ -f "master.zip" ]; then
  #rm master.zip
#fi
#wget https://github.com/cornernote/minetest-home_gui/archive/master.zip
#mv master.zip minetest-home_gui.zip
#unzip minetest-home_gui.zip
#sudo mv minetest-home_gui-master/home_gui "$MT_MYGAME_MODS_PATH/home_gui"

#echo "snow:snow 255 255 255" >> $HOME/minetest/util/colors.txt
#echo "snow:snow_block 255 255 255" >> $HOME/minetest/util/colors.txt
#echo "snow:ice 144 217 234" >> $HOME/minetest/util/colors.txt

#sh chunkymap/install-ubuntu.sh

cd "$HOME/Downloads"
#does NOT have a zip extension when downloaded via wget:
MTMOD_SRC_ZIP=mesecons_modpack.zip
MTMOD_UNZ_NAME=mesecons-master
MTMOD_DEST_NAME=mesecons
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf $MTMOD_UNZ_NAME
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
wget -O $MTMOD_SRC_ZIP https://github.com/minetest-mods/mesecons/archive/master.zip
unzip $MTMOD_SRC_ZIP
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
sudo mv -f $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to create $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi

############ REQUIRES MESECONS ############
##### NEEDED since carts in minetest_game added much of this functionality but not yet startstoprail or detectorrail #####
#See also carts plus, a fork of carts (the PilzAdam one later added to minetest_game) https://github.com/Kilarin/minetest-mod-carts-plus which adds touring rails, a hand break, switching, and view locking
#NOTE: boost_cart has handbrake (back key), Rail junction switching with the 'right-left' walking keys
#So either install this mod or do (less functionality):
#minetest.register_alias("boost_cart:detectorrail", "carts:rail")
#minetest.register_alias("boost_cart:startstoprail", "carts:powerrail")
#-- carts:brakerail
#-- carts:cart
#-- carts:powerrail
#-- carts:rail
cd "$HOME/Downloads"
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=boost_cart.zip
MTMOD_UNZ_NAME=boost_cart-master
MTMOD_DEST_NAME=boost_cart
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf $MTMOD_UNZ_NAME
fi
if [ -f "$MTMOD_DL_ZIP" ]; then
  rm -f "$MTMOD_DL_ZIP"
fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
wget https://github.com/SmallJoker/boost_cart/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
#https://forum.minetest.net/viewtopic.php?f=11&t=10172&hilit=boost+cart
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi

cd "$HOME/Downloads"
#MTMOD_DL_ZIP=archive.zip
#MTMOD_SRC_ZIP=throwing_Echoes91.zip
#MTMOD_SRC_ZIP=throwing_MinetestForFun.zip
MTMOD_SRC_ZIP=throwing_minetest-mods.zip
#MTMODPACK_UNZ_NAME=server-minetestforfun-master
MTMOD_UNZ_NAME=throwing-master
MTMOD_DEST_NAME=throwing
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -d "$MTMOD_DEST_PATH" ]; then
  echo "Removing old version of throwing..."
  sudo rm -Rf $MTMOD_DEST_PATH
fi
#echo "Installing MinetestForFun's PvP fork of Echoes91's (NOT Echoes91's Throwing enhanced NOT PilzAdam's NOT Jeija's) Throwing <https://forum.minetest.net/viewtopic.php?f=11&t=11437>"
if [ -f "throwing_Echoes91.zip" ]; then
  rm throwing_Echoes91.zip
fi
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf $MTMOD_UNZ_NAME
fi
#if [ -d "$MTMODPACK_UNZ_NAME" ]; then
#  rm -Rf $MTMODPACK_UNZ_NAME
#fi
if [ -f "$MTMOD_SRC_ZIP" ]; then
  rm -f "$MTMOD_SRC_ZIP"
fi
#wget -O $MTMOD_SRC_ZIP https://github.com/PilzAdam/throwing/zipball/master
#wget -O $MTMOD_SRC_ZIP https://gitlab.com/echoes91/throwing/repository/archive.zip
#wget -O $MTMOD_SRC_ZIP https://github.com/MinetestForFun/server-minetestforfun/archive/master.zip
wget -O $MTMOD_SRC_ZIP https://github.com/minetest-mods/throwing/archive/master.zip
echo "Installing minetest-mods' (NOT MinetestForFun's PvP fork of Echoes91's, NOT Echoes91's Throwing enhanced NOT PilzAdam's NOT Jeija's) Throwing <https://forum.minetest.net/viewtopic.php?f=11&t=11437>"
#mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi

cd $HOME/Downloads
MTMOD_SRC_ZIP=throwing_arrows.zip
MTMOD_UNZ_NAME=throwing_arrows-master
MTMOD_DEST_NAME=throwing_arrows
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf $MTMOD_UNZ_NAME
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
wget -O $MTMOD_SRC_ZIP https://github.com/minetest-mods/throwing_arrows/archive/master.zip
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
sudo rm -Rf "$MTMOD_DEST_PATH/etc"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi


cd "$HOME/Downloads"
#MTMOD_DL_ZIP=*
MTMOD_SRC_ZIP=tsm_mines.zip
#MTMOD_UNZ_NAME=tsm_mines-*
MTMOD_UNZ_NAME=tsm_mines
MTMOD_DEST_NAME=tsm_mines
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -d tsm_mines ]; then
  rm -Rf tsm_mines
fi
if [ -f tsm_mines.zip ]; then
  rm tsm_mines.zip
fi
if [ -d tsm_mines_zipped ]; then
  rm -Rf tsm_mines_zipped
fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
#if [ ! -d tsm_mines_zipped ]; then
#  mkdir tsm_mines_zipped
#fi
#cd tsm_mines_zipped
#wget http://repo.or.cz/w/tsm_mines.git/snapshot/7ff7f5c24c05b463ecfbf80cbd5e8f6f4a4f4520.zip
#wget http://repo.or.cz/tsm_mines.git/shortlog/refs/heads/master
#mv master master.zip
#unzip master.zip
#unzip *
git clone git://repo.or.cz/tsm_mines.git
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi

cd "$HOME/Downloads"
#MTMOD_DL_ZIP=*
MTMOD_SRC_ZIP=tsm_railcorridors.zip
#MTMOD_UNZ_NAME=tsm_railcorridors-*
MTMOD_UNZ_NAME=tsm_railcorridors
MTMOD_DEST_NAME=tsm_railcorridors
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -d $MTMOD_DEST_NAME ]; then
  rm -Rf $MTMOD_DEST_NAME
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
if [ -d tsm_railcorridors_zipped ]; then
  rm -Rf tsm_railcorridors_zipped
fi
#if [ ! -d tsm_railcorridors_zipped ]; then
#  mkdir tsm_railcorridors_zipped
#fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
#cd "tsm_railcorridors_zipped"
#wget http://repo.or.cz/w/RailCorridors/tsm_railcorridors.git/snapshot/7fab088e813b777ceddaa56fc980ccc55b0b3f01.zip
git clone git://repo.or.cz/RailCorridors/tsm_railcorridors.git
#unzip *
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi

cd "$HOME/Downloads"
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=fishing_Minetestforfun.zip
MTMOD_UNZ_NAME=fishing-master
MTMOD_DEST_NAME=fishing
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
echo "Installing Minetestforfun's (NOT wulfsdad's) fishing <https://forum.minetest.net/viewtopic.php?f=11&t=13659>"
echo "Installing Minetestforfun's (NOT wulfsdad's) fishing <https://forum.minetest.net/viewtopic.php?f=11&t=13659>" >> $MTMOD_SRC_ZIP.txt
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf $MTMOD_UNZ_NAME
fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
wget https://github.com/MinetestForFun/fishing/archive/master.zip
mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi

cd "$HOME/Downloads"
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=compassgps.zip
MTMOD_UNZ_NAME=compassgps-master
MTMOD_DEST_NAME=compassgps
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
echo "Installing Kilarin's compassgps (NOT TeTpaAka, nor Echo, nor PilzAdam compass) <https://forum.minetest.net/viewtopic.php?t=9373>"
echo "Installing Kilarin's compassgps (NOT TeTpaAka, nor Echo, nor PilzAdam compass) <https://forum.minetest.net/viewtopic.php?t=9373>" >> $MTMOD_SRC_ZIP.txt
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf $MTMOD_UNZ_NAME
fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
wget https://github.com/Kilarin/compassgps/archive/master.zip
mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi

MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=whitelist.zip
MTMOD_UNZ_NAME=whitelist-master
MTMOD_DEST_NAME=whitelist
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
echo "Installing ShadowNinja's whitelist <https://forum.minetest.net/viewtopic.php?id=8434>"
echo "Installing ShadowNinja's whitelist <https://forum.minetest.net/viewtopic.php?id=8434>" >> $MTMOD_SRC_ZIP.txt
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf $MTMOD_UNZ_NAME
fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
wget https://github.com/ShadowNinja/whitelist/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi


MTMOD_DEST_NAME=playereffects
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -f playereffects_Wuzzy.zip ]; then
  rm playereffects_Wuzzy.zip
fi
if [ -f "3b860c74ae9803f9a979b12c6f6beb74f96ae62c.zip" ]; then
  rm "3b860c74ae9803f9a979b12c6f6beb74f96ae62c.zip"
fi
if [ -d "minetest_playereffects-3b860c7" ]; then
  rm -Rf minetest_playereffects-3b860c7
fi
if [ -d "minetest_playereffects" ]; then
  rm -Rf minetest_playereffects
fi
cd "$HOME/Downloads"
git clone http://repo.or.cz/minetest_playereffects.git
#wget http://repo.or.cz/minetest_playereffects.git/snapshot/3b860c74ae9803f9a979b12c6f6beb74f96ae62c.zip
#mv "3b860c74ae9803f9a979b12c6f6beb74f96ae62c.zip" playereffects_Wuzzy.zip
#unzip playereffects_Wuzzy.zip
#sudo mv minetest_playereffects* "$MT_MYGAME_MODS_PATH/playereffects"
sudo mv minetest_playereffects "$MTMOD_DEST_PATH"

#Byakuren. <https://forum.minetest.net/viewtopic.php?f=9&t=13941>.

#monoidal_effects by Byakuren [raymoo on GitHub] is deprecated by player_monoids by Byakuren [raymoo on GitHub] +playereffects by Wuzzy
#according to the author https://forum.minetest.net/viewtopic.php?t=13941
#cd $HOME\Downloads
#MTMOD_DL_ZIP=master.zip
#MTMOD_SRC_ZIP=monoidal_effects.zip
#MTMOD_UNZ_NAME=monoidal_effects-master
#MTMOD_DEST_NAME=monoidal_effects
#MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
#  rm -Rf $MTMOD_UNZ_NAME
#fi
#if [ -f $MTMOD_DL_ZIP ]; then
#  rm -f $MTMOD_DL_ZIP
#fi
#if [ -f $MTMOD_SRC_ZIP ]; then
#  rm $MTMOD_SRC_ZIP
#fi
#wget https://github.com/minetest-mods/monoidal_effects/archive/master.zip
#mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
#unzip $MTMOD_SRC_ZIP
#sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
#if [ ! -d "$MTMOD_DEST_PATH" ]; then
#  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
#  cat $err_txt
#  sleep 3
#  exit 1
#fi

cd $HOME\Downloads
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=player_monoids.zip
MTMOD_UNZ_NAME=player_monoids-master
MTMOD_DEST_NAME=player_monoids
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf $MTMOD_UNZ_NAME
fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm $MTMOD_SRC_ZIP
fi
wget https://github.com/minetest-mods/player_monoids/archive/master.zip
mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
unzip $MTMOD_SRC_ZIP
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi


cd "$HOME/Downloads"
MTMOD_DL_ZIP=master
MTMOD_SRC_ZIP=worldedit.zip
MTMOD_UNZ_NAME=Uberi-Minetest-WorldEdit-*
MTMOD_DEST_NAME=worldedit
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
echo "Installing sfan5's  <https://forum.minetest.net/viewtopic.php?t=572>"
echo "Installing sfan5's  <https://forum.minetest.net/viewtopic.php?t=572>" >> $MTMOD_SRC_ZIP.txt
if [ -f $MTMOD_DL_ZIP ]; then
  rm $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm $MTMOD_SRC_ZIP
fi
rm -Rvf $MTMOD_UNZ_NAME
#wget https://github.com/Uberi/MineTest-WorldEdit/zipball/master
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
sudo mv -f $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi

# add_zipped_mod worldedit Uberi-Minetest-WorldEdit-* https://github.com/Uberi/MineTest-WorldEdit/zipball/master
# add_zipped_mod worldedit Minetest-WorldEdit-* https://github.com/Uberi/MineTest-WorldEdit/zipball/master
add_git_clone_mod worldedit Uberi-Minetest-WorldEdit https://github.com/Uberi/Minetest-WorldEdit.git

#MarkBu's ambience/ambiance ambient sounds (burli on https://forum.minetest.net/viewtopic.php?f=9&t=14814 )
#add_zipped_mod ambianceplus ambianceplus-master https://github.com/MarkuBu/ambianceplus/archive/master.zip

# tenplus1's ambience/ambiance ambient sounds (fork linked at original's thread at https://forum.minetest.net/viewtopic.php?f=11&t=2807&start=275 )
add_zipped_mod ambience ambience-master https://github.com/tenplus1/ambience/archive/master.zip
# expertmm fork of LeMagnesium's minetest-mod-metatools
add_zipped_mod metatools minetest-mod-metatools-master https://github.com/expertmm/minetest-mod-metatools/archive/master.zip
#[mod-pack] sky critters (for mobs_redo) [mobs_sky] <https://forum.minetest.net/viewtopic.php?f=9&t=12688>
#requires mobs redo
add_zipped_mod mobs_sky mobs_sky-master https://github.com/blert2112/mobs_sky/archive/master.zip

# forum_url: https://forum.minetest.net/viewtopic.php?f=11&t=13857
# description:
# * REPLACES pyramids.
# * Works with mobs_redo and creatures.
# * optionally makes use of fire (in minetest_game; only uses fire:flint_and_steel), mobs, creatures, bones, xpanes (now part of minetest_game)
# * only RECIPES require fake_fire and xpanes
# * NOW (2017-2018) IS A MODPACK: formerly was a mod named spawners, now is a modpack containing:
#   * spawners_env: appears in Dungeons and Temples (the pink stone ones); spawns hostile mobs; has small chance of spawning a spawner
#   * spawners_mobs: spawns non-hostile mobs
#   * spawners_ores: spawns ores
add_zipped_mod spawners minetest_gamers-spawners-* https://bitbucket.org/minetest_gamers/spawners/get/master.zip
MTMOD_DEST_NAME=spawners/spawners_ores
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ -d "$MTMOD_DEST_PATH" ]; then
  echo "removing $MTMOD_DEST_NAME..."
  sudo rm -Rf "$MTMOD_DEST_PATH"
else
  echo "ERROR: could not find $MTMOD_DEST_PATH for removal, so cancelling ENLIVEN install"
  sleep 3
  exit 1
fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: could not remove $MTMOD_DEST_PATH for removal, so cancelling ENLIVEN install"
  sleep 3
  exit 1
fi
echo "SPAWN_PYRAMIDS = true" > settings.txt
echo "SPAWNERS_GENERATE = true" >> settings.txt
echo "CHESTS_GENERATE = true" >> settings.txt
sudo mv settings.txt "$MTMOD_DEST_PATH/"
echo "NOTE: in spawners, only SPAWNERS_GENERATE or CHESTS_GENERATE, not both (SPAWNERS_GENERATE overrides) spawn in world for now. See thread for updated info: https://forum.minetest.net/viewtopic.php?f=11&t=13857&start=25"
echo "see also expertmm's game-install-enliven-testing-SPAWNERS_BOTH_DEBUG.txt"

# forum_url: https://forum.minetest.net/viewtopic.php?t=12189
# description: Adds animations to the players' head
add_zipped_mod playeranim playeranim-master https://github.com/minetest-mods/playeranim/archive/master.zip
add_zipped_mod homedecor_modpack homedecor_modpack-master https://github.com/minetest-mods/homedecor_modpack/archive/master.zip
# expertmm fork of a rather non-maintained mod--forum link is at https://forum.minetest.net/viewtopic.php?id=3663
# (original mod was at https://github.com/Doc22/birthstones-mod/archive/master.zip)
add_zipped_mod birthstones minetest-birthstones-master https://github.com/expertmm/minetest-birthstones/archive/master.zip
add_zipped_mod bakedclay bakedclay-master https://github.com/tenplus1/bakedclay/archive/master.zip
# https://forum.minetest.net/viewtopic.php?f=11&t=12440&p=310915#p310915
# wget https://forum.minetest.net/download/file.php?id=6140
# forum link file.php?id=6140 changed, so use salahzar's GitHub upload instead:
add_zipped_mod invhack minetest-invhack-master https://github.com/salahzar/minetest-invhack/archive/master.zip
add_zipped_mod unifieddyes unifieddyes-master https://github.com/minetest-mods/unifieddyes/archive/master.zip
#Sokomine's original version has no security ( https://forum.minetest.net/viewtopic.php?id=4877 )
#  https://github.com/Sokomine/travelnet/archive/master.zip
add_zipped_mod travelnet travelnet-master https://github.com/expertmm/travelnet/archive/master.zip
add_zipped_mod anvil anvil-master https://github.com/minetest-mods/anvil/archive/master.zip
add_zipped_mod sling sling-master https://github.com/minetest-mods/sling/archive/master.zip
#REPLACES PilzAdam's, modified by kaeza, maintained by VenessaE; FORMERLY in homedecor_modpack
#forum post: https://forum.minetest.net/viewtopic.php?t=13762
# kaeza's signs_lib (forked from PilzAdam's and TheXYZ's code) was moved here from: https://github.com/kaeza/minetest-signs_lib-extrafonts/archive/master.zip
add_zipped_mod signs_lib signs_lib-master https://github.com/minetest-mods/signs_lib/archive/master.zip
# EXTRA FONTS PACK for signs_lib DOESN'T SEEM TO WORK IN MULTIPLAYER, and is unwieldy to use:
#cd $HOME/Downloads
#MTMOD_DL_ZIP=master.zip
#MTMOD_SRC_ZIP=minetest-signs_lib-extrafonts.zip
#MTMOD_UNZ_NAME=minetest-signs_lib-extrafonts-master
#MTMOD_DEST_NAME=signs_lib/textures
#MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
#if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
#  rm -Rf $MTMOD_UNZ_NAME
#fi
#if [ -f $MTMOD_DL_ZIP ]; then
#  rm -f $MTMOD_DL_ZIP
#fi
#if [ -f $MTMOD_SRC_ZIP ]; then
#  rm -f $MTMOD_SRC_ZIP
#fi
#if [ -d "$MTMOD_DEST_PATH" ]; then
#  sudo rm -Rf "$MTMOD_DEST_PATH"
#fi
#wget https://github.com/kaeza/minetest-signs_lib-extrafonts/archive/master.zip
#mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
#unzip "$MTMOD_SRC_ZIP"
##sudo cp -f $MTMOD_UNZ_NAME/15px/* "$MTMOD_DEST_PATH/"
#sudo cp -f $MTMOD_UNZ_NAME/31px/* "$MTMOD_DEST_PATH/"
#if [ ! -d "$MTMOD_DEST_PATH" ]; then
#  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
#  cat $err_txt
#  sleep 3
#  exit 1
#fi

cd $HOME/Downloads
MTMOD_DL_ZIP=master.zip
MTMOD_SRC_ZIP=farming.zip
MTMOD_UNZ_NAME=farming-master
MTMOD_DEST_NAME=farming
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf $MTMOD_UNZ_NAME
fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  # remove old copy, or remove minetest_game's farming
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
wget https://github.com/tenplus1/farming/archive/master.zip
mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi

#Forum post: https://forum.minetest.net/viewtopic.php?f=11&t=10423
#Wuzzy's slimenodes mod (only available via give).
cd "$HOME/Downloads"
#MTMOD_DL_ZIP=master.zip
#MTMOD_SRC_ZIP=slimenodes.zip
#MTMOD_UNZ_NAME=slimenodes-master
MTMOD_UNZ_NAME=minetest_slimenodes
MTMOD_DEST_NAME=slimenodes
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf $MTMOD_UNZ_NAME
fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
# web view: http://repo.or.cz/w/minetest_slimenodes.git
git clone git://repo.or.cz/minetest_slimenodes.git
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi

#(a trmp is just a modpack of TRMs for treasurer. At least one trm must be installed for treasurer to to anything)
cd $HOME/Downloads
#MTMOD_DL_ZIP=file.php?id=1301
MTMOD_SRC_ZIP=trmp_minetest_game.zip
MTMOD_UNZ_NAME=trmp_minetest_game
MTMOD_DEST_NAME=trmp_minetest_game
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
if [ ! -z "`ls | grep $MTMOD_UNZ_NAME`" ]; then  # works with wildcard in variable
  rm -Rf $MTMOD_UNZ_NAME
fi
if [ -f $MTMOD_DL_ZIP ]; then
  rm -f $MTMOD_DL_ZIP
fi
if [ -f $MTMOD_SRC_ZIP ]; then
  rm -f $MTMOD_SRC_ZIP
fi
if [ -d "$MTMOD_DEST_PATH" ]; then
  sudo rm -Rf "$MTMOD_DEST_PATH"
fi
wget -O $MTMOD_SRC_ZIP https://forum.minetest.net/download/file.php?id=1301
#mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
unzip "$MTMOD_SRC_ZIP"
sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
if [ ! -d "$MTMOD_DEST_PATH" ]; then
  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
fi


# NOTE: a skin database is at http://minetest.fensta.bplaced.net/
# bell07's 2016 (FORK of Krock's fork of dmonty's) u_skins (u_skins is a skin GUI that works with unified_inventory, whereas other skin GUIs often use inventory++)
# Krock's is outdated and has remaining bugs such as in updater: wget https://github.com/SmallJoker/minetest-u_skinsdb/archive/master.zip
# bell07's no longer exists
# wget https://github.com/bell07/minetest-u_skinsdb/archive/master.zip
# add_zipped_mod u_skins minetest-u_skinsdb-master https://github.com/dmonty2/minetest-u_skinsdb/archive/master.zip
#add_zipped_mod u_skins minetest-u_skinsdb-master https://github.com/dmonty2/minetest-u_skinsdb/archive/master.zip
# add_zipped_mod skinsdb minetest-u_skinsdb-master https://github.com/dmonty2/minetest-u_skinsdb/archive/master.zip
# forked and is now a part of minetest-mods thanks to bell07
MATCHING_MODS_BEFORE="`ls $MT_MYGAME_MODS_PATH | grep skin`"
remove_mod u_skinsdb
remove_mod u_skins
PATCH_SKINS_MOD_NAME="skinsdb"  # used further down too!
add_zipped_mod $PATCH_SKINS_MOD_NAME skinsdb-master https://github.com/minetest-mods/skinsdb/archive/master.zip
if [ ! -z "$MATCHING_MODS_BEFORE" ]; then
  echo "Removed $MATCHING_MODS_BEFORE then installed $PATCH_SKINS_MOD_NAME"
fi
# Update skins database (WARNING: skin numbering affects chosen player skin):
# (jq is a json processor, required for the updater bash script:)
# sudo apt-get -y install jq
# cd "$MTMOD_DEST_PATH"
# cd u_skins  #bell07's version is a mod, not a modpack
# cd updater
# NOTE:
# Only download entire skins database if you
# REALLY, REALLY MEAN IT:
# ./update_skins_db.sh
# (note, bell07 has the fixed bash script, but the python3 script is still bugged as of 2016-01-29, and includes a .NET assembly that seems to only work for Windows (has meta directory not found error on mono for Linux)
# PATCH FURTHER DOWN WILL REMOVE EXISTING SKINS AND ONLY ADD EnlivenMinetest skins from patches folder

echo
echo
echo
if [ -d "$PATCHES_PATH" ]; then
  echo "adding the following necessary integration mods:"
  ls $PATCHES_PATH/mods-integration/
  sudo cp -R $PATCHES_PATH/mods-integration/* "$MT_MYGAME_MODS_PATH/"
  echo
  echo "adding the following multiplayer mods:"
  ls $PATCHES_PATH/mods-multiplayer/
  sudo cp -R $PATCHES_PATH/mods-multiplayer/* "$MT_MYGAME_MODS_PATH/"
  echo "adding non-manual patches to subgame (vs minetest_game and downloaded mods):"
  echo "patching $MT_MYGAME_DIR (files only, so 'omitting directory' warnings are ok)..."
  sudo cp -f $PATCHES_PATH/subgame/* "$MT_MYGAME_DIR/"
  echo "patching $MT_MYGAME_DIR (files only, so 'omitting directory' warnings are ok)..."
  sudo cp -f $PATCHES_PATH/subgame/menu/* "$MT_MYGAME_DIR/menu/"
  echo "patching $MT_MYGAME_DIR (files only, so 'omitting directory' warnings are ok)..."
  sudo cp -f $PATCHES_PATH/subgame/mods/mobs/textures/* "$MT_MYGAME_DIR/mods/mobs/textures/"
  echo "patching $MT_MYGAME_DIR (files only, so 'omitting directory' warnings are ok)..."
  sudo cp -f $PATCHES_PATH/subgame/mods/mobs_monster/textures/* "$MT_MYGAME_DIR/mods/mobs_monster/textures/"

# REMOVE EXISTING SKINS AND ONLY ADD expertmm skins:
MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$PATCH_SKINS_MOD_NAME
SUB_NAME="textures"  # include u_skins since u_skins/u_skins IS THE MOD in the modpack
SUB_PATH="$MTMOD_DEST_PATH/$SUB_NAME"
if [ -d "$SUB_PATH" ]; then
  echo "removing original $SUB_PATH/character_*..."
  rm -Rf $SUB_PATH/character_*  # cannot have quotes if using wildcards
fi
sudo cp -f $PATCHES_PATH/mods-multiplayer/$PATCH_SKINS_MOD_NAME/$SUB_NAME "$SUB_PATH"
if [ ! -d "$SUB_PATH" ]; then
  echo "ERROR: failed to install expertmm's skins to $SUB_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
else
  echo "installed expertmm's skins to $SUB_PATH"
fi
SUB_NAME="meta"  # include u_skins since u_skins/u_skins IS THE MOD in the modpack
SUB_PATH="$MTMOD_DEST_PATH/$SUB_NAME"
if [ -d "$SUB_PATH" ]; then
  echo "removing original $SUB_PATH/character_*..."
  rm -Rf $SUB_PATH/character_*  # cannot have quotes if using wildcards
fi
sudo cp -f $PATCHES_PATH/mods-multiplayer/$PATCH_SKINS_MOD_NAME/$SUB_NAME "$SUB_PATH"
if [ ! -d "$SUB_PATH" ]; then
  echo "ERROR: failed to install expertmm's skins to $SUB_PATH, so cannot continue." > $err_txt
  cat $err_txt
  sleep 3
  exit 1
else
  echo "installed metadata for expertmm's skins to $SUB_PATH"
fi



  echo "mods affected: mobs mobs_monsters $PATCH_SKINS_MOD_NAME"
  PATCHED_FLAG=""
  BASIS_PATH=$PATCHES_PATH/subgame-basis/mods/bones/init.lua
  MODIFIED_PATH=$PATCHES_PATH/subgame/mods/bones/init.lua
  MTMOD_DEST_NAME=bones
  MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/bones
  TARGET_PATH=$MTMOD_DEST_PATH/init.lua
  TRY_DIFF="`diff $BASIS_PATH $TARGET_PATH`"
  if [ -z "$TRY_DIFF" ]; then
    sudo cp -f $MODIFIED_PATH "$MT_MYGAME_DIR/mods/bones/"
    echo "done attempting to patch $MTMOD_DEST_PATH/"
  else
    echo "FAILED to patch $MTMOD_DEST_NAME since $TARGET_PATH differs from known version (this is not a problem if you ran the patcher more than once)."
  fi
  BASIS_PATH=$PATCHES_PATH/subgame-basis/mods/homedecor_modpack/homedecor/gastronomy.lua
  MODIFIED_PATH=$PATCHES_PATH/subgame/mods/homedecor_modpack/homedecor/gastronomy.lua
  TARGET_PATH=$MT_MYGAME_MODS_PATH/homedecor_modpack/homedecor/gastronomy.lua
  MTMOD_DEST_NAME=homedecor_modpack
  MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/homedecor_modpack/homedecor
  TRY_DIFF="`diff $BASIS_PATH $TARGET_PATH`"
  if [ -z "$TRY_DIFF" ]; then
    sudo cp -f $MODIFIED_PATH "$MTMOD_DEST_PATH/"
    echo "done attempting to patch $MTMOD_DEST_PATH/"
  else
    echo "FAILED to patch $MTMOD_DEST_NAME since $TARGET_PATH differs from known version (this is not a problem if you ran the patcher more than once)."
  fi
  BASIS_PATH=$PATCHES_PATH/subgame-basis/mods/homedecor_modpack/homedecor/crafts.lua
  MODIFIED_PATH=$PATCHES_PATH/subgame/mods/homedecor_modpack/homedecor/crafts.lua
  TARGET_PATH=$MT_MYGAME_MODS_PATH/homedecor_modpack/homedecor/crafts.lua
  MTMOD_DEST_NAME=homedecor_modpack
  TRY_DIFF="`diff $BASIS_PATH $TARGET_PATH`"
  if [ -z "$TRY_DIFF" ]; then
    sudo cp -f $MODIFIED_PATH "$MTMOD_DEST_PATH/"
    echo "done attempting to patch $MTMOD_DEST_PATH/"
  else
    echo "FAILED to patch $MTMOD_DEST_NAME since $TARGET_PATH differs from known version (this is not a problem if you ran the patcher more than once)."
  fi
  if [ -d "$PATCHES_PATH/subgame/mods/homedecor_modpack/homedecor/models" ]; then
    # deprecated, but copy in case gets un-deprecated
    cp -f $PATCHES_PATH/subgame/mods/homedecor_modpack/homedecor/models/* "$MTMOD_DEST_PATH/models/"
  fi
  # NOTE: quotes don't work with wildcard
  cp -f $PATCHES_PATH/subgame/mods/homedecor_modpack/homedecor/textures/* "$MTMOD_DEST_PATH/textures/"
  echo "# not recommended:"
  echo "sudo cp -Rf $PATCHES_PATH/mods-stopgap/* $MT_MYGAME_MODS_PATH/"
  echo "sudo rm -Rf $MT_MYGAME_MODS_PATH/1.nonworking"
else
  echo "did not find $PATCHES_PATH, so skipped automatic patching which is partially implemented"
fi
echo
echo "# remove not available on 0.4.16 stable (is only avail on 0.4.16-dev or higher)"
echo "sudo rm -Rf /usr/share/games/minetest/games/ENLIVEN/mods/worldedit/worldedit_brush"
echo
echo
echo
echo "#### $MT_MYWORLD_DIR/world.mt: ####"
cat "$MT_MYWORLD_DIR/world.mt"
echo "### end $MT_MYWORLD_DIR/world.mt ##"
echo ""
echo ""
echo ""
#echo "Remember, if you are using Better HUD + Hunger, add the values for the new meat to hunger.lua"
#echo "--see <https://forum.minetest.net/viewtopic.php?f=11&t=9917&hilit=mobs>"
echo "NOTE: hud_hunger/hunger/food.lua now comes with values for food from mobs."
#hud_hunger now includes mobs food (see /usr/local/share/minetest/games/enliven/mods/hud_hunger/hunger/food.lua )
echo ""
echo "NOW MAKE SURE YOU EDIT $MT_MYGAME_MODS_PATH/protector/init.lua near line 325 to block comment ( --[[ then afterward --]]) the on_rightclick registration (since protection block right-clicked by its owner crashes server)"
echo "Then make sure you login, REMEMBERING to put a password in second box, then logout then:"
echo "  nano $MT_MYWORLD_DIR/players/username where username is YOUR username, give yourself the following permissions to edit areas, edit protector blocks (and other protector nodes), and do other things: areas,delprotect,home,noclip,fly,rollback,settime,teleport,bring,fast,password,give,ban,privs,kick,worldedit"
echo "  bring: allows to you teleport other players"
echo "  ban: allows /ban ip and /unban ip (and /whitelist add player and /whitelist remove player commands if whitelist mod is installed)"
echo "  kick: allows /kick player"
echo "  privs: allows grant and revoke commands"
echo "  delprotect: circumvents protector blocks, including allowing removing them"
echo "  invhack: editing player inventories as moderator"
echo ""
echo "  * for invhack, remember to do: /giveme invhack:tool"
echo "  * uncomment columns in lapis mod"
echo "  * Make sure client (server done already above) minetest.conf has secure.trusted_mods = advanced_npc"
echo "  * Make sure writable minetest conf was successfully written"
echo "    over $MT_MYGAME_DIR/minetest.conf with (NOTE: protector_drop is deprecated):"
echo "protector_radius = 7"
echo "protector_pvp = true"
echo "protector_pvp_spawn = 10"
echo "protector_drop = false"
echo "protector_hurt = 3"
echo ""
echo "default_privs = interact,shout,home"
echo "max_users = 50"
echo "motd = \"Actions and chat messages are logged. Visit fcacloud.com/minetest for recipes and live map.\""
echo "disallow_empty_passwords = true"
echo ""
echo "#not all settings can be changed in this minetest.conf (see minetest.conf.example in THIS folder)"
echo "#some settings can only be changed in client's local copy of minetest.conf (see or login scripts in network)"

