#!/bin/sh
echo "WARNING: mts-ENLIVEN script is deprecated--instead, run:"
try_path="./GitHub/EnlivenMinetest/mtsenliven.py"
if [ -f "$try_path" ]; then
  echo "  python3 $try_path"
else
  try_path="$HOME/GitHub/EnlivenMinetest/mtsenliven.py"
  if [ -f "$try_path" ]; then
    echo "  python3 $try_path"
  else
    echo "  python3 mtsenliven.py"
  fi
fi
# sleep 4
# exit 1
mts=minetestserver
if [ ! -f "`command -v minetestserver`" ]; then
  try_path="$HOME/minetest/bin/minetestserver"
  if [ -f "$try_path" ]; then
    mts="$try_path"
  fi
fi
# BROKEN: screen -t MinetestServer minetestserver --gameid minetest_next --draworigin --drawplayers --world FCAWorldMTNext
# BROKEN: screen -t MinetestServer minetestserver --gameid ENLIVEN --worldname FCAGameAWorld
# NOTE: if only title is set, screen -x must be used to resume, so use -S <name> to resume with -r <name>
# screen -S MinetestServer minetestserver --gameid ENLIVEN --worldname FCAGameAWorld
# screen -S MinetestServer /home/owner/minetest/bin/minetestserver --gameid ENLIVEN --worldname FCAGameAWorld
MT_MYWORLD_NAME="FCAWorldB"
screen -S MinetestServer $mts --gameid ENLIVEN --worldname $MT_MYWORLD_NAME
if [ ! -d "$HOME/.minetest/worlds/" ]; then
  echo "ERROR: missing $HOME/.minetest/worlds/$MT_MYWORLD_NAME"
fi
